<?php
declare(strict_types=1);
$active_module='distribution'; require_once __DIR__.'/layout.php';
if(empty($_SESSION['supplier_csrf']))$_SESSION['supplier_csrf']=bin2hex(random_bytes(32)); $u=$supplier_user;$pdo=db();$message='';$error='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($_SESSION['supplier_csrf'],(string)($_POST['csrf']??'')))throw new RuntimeException('Güvenlik doğrulaması geçersiz.');$action=$_POST['action']??'';
 if($action==='connection'){$code=strtolower(trim((string)$_POST['channel_code']));$name=trim((string)$_POST['display_name']);if(!preg_match('/^[a-z0-9_]{2,60}$/',$code)||$name==='')throw new RuntimeException('Kanal kodu ve görünen ad zorunludur.');$scopes=['availability'=>isset($_POST['availability']),'rates'=>isset($_POST['rates']),'restrictions'=>isset($_POST['restrictions']),'reservations'=>isset($_POST['reservations'])];$pdo->prepare("INSERT INTO channel_connections(supplier_id,channel_code,display_name,property_code,access_token,sync_scopes,status) VALUES(?,?,?,?,?,?::jsonb,'draft') ON CONFLICT(supplier_id,channel_code) DO UPDATE SET display_name=EXCLUDED.display_name,property_code=EXCLUDED.property_code,sync_scopes=EXCLUDED.sync_scopes")->execute([$u['supplier_id'],$code,$name,trim((string)$_POST['property_code'])?:null,bin2hex(random_bytes(32)),json_encode($scopes)]);$message='Kanal bağlantısı ve ARI yetkileri kaydedildi.';}
 if($action==='property_map'){$connection=(int)$_POST['connection_id'];$property=(int)$_POST['property_id'];$external=trim((string)$_POST['external_property_id']);if(!$connection||!$property||$external==='')throw new RuntimeException('Kanal, ürün ve dış sistem ürün kodu zorunludur.');$check=$pdo->prepare('SELECT id FROM channel_connections WHERE id=? AND supplier_id=?');$check->execute([$connection,$u['supplier_id']]);if(!$check->fetch())throw new RuntimeException('Bağlantı yetkisi bulunamadı.');$pdo->prepare("INSERT INTO channel_property_mappings(channel_connection_id,property_id,external_property_id) VALUES(?,?,?) ON CONFLICT(channel_connection_id,property_id) DO UPDATE SET external_property_id=EXCLUDED.external_property_id,status='active'")->execute([$connection,$property,$external]);$message='Ürün eşleştirmesi kaydedildi.';}
 if($action==='queue'){$connection=(int)$_POST['connection_id'];$scope=$_POST['scope']??'availability';if(!in_array($scope,['availability','rates','restrictions','content'],true))throw new RuntimeException('Geçersiz senkronizasyon alanı.');$check=$pdo->prepare('SELECT id FROM channel_connections WHERE id=? AND supplier_id=?');$check->execute([$connection,$u['supplier_id']]);if(!$check->fetch())throw new RuntimeException('Bağlantı yetkisi bulunamadı.');$pdo->prepare("INSERT INTO channel_sync_logs(channel_connection_id,direction,scope,status,request_payload) VALUES(?,'push',?,'queued','{}')")->execute([$connection,$scope]);$message='Senkronizasyon işi kuyruğa eklendi.';}
}}
catch(Throwable $e){$error=$e->getMessage();}
// Migration 044 öncesi kayıtlar için token'ları uçur (UNIQUE index token üretirken takılmasın).
$q=$pdo->query("SELECT id FROM channel_connections WHERE access_token IS NULL OR access_token='' FOR UPDATE SKIP LOCKED");$missing=$q->fetchAll();foreach($missing as $m){$pdo->prepare('UPDATE channel_connections SET access_token=? WHERE id=?')->execute([bin2hex(random_bytes(32)),$m['id']]);}
$q=$pdo->prepare('SELECT * FROM channel_connections WHERE supplier_id=? ORDER BY id DESC');$q->execute([$u['supplier_id']]);$connections=$q->fetchAll();$q=$pdo->prepare('SELECT id,name FROM properties WHERE supplier_id=? ORDER BY name');$q->execute([$u['supplier_id']]);$properties=$q->fetchAll();$q=$pdo->prepare('SELECT m.*,c.display_name,p.name property_name FROM channel_property_mappings m JOIN channel_connections c ON c.id=m.channel_connection_id JOIN properties p ON p.id=m.property_id WHERE c.supplier_id=? ORDER BY m.id DESC');$q->execute([$u['supplier_id']]);$mappings=$q->fetchAll();$q=$pdo->prepare('SELECT l.*,c.display_name FROM channel_sync_logs l JOIN channel_connections c ON c.id=l.channel_connection_id WHERE c.supplier_id=? ORDER BY l.id DESC LIMIT 30');$q->execute([$u['supplier_id']]);$logs=$q->fetchAll();
supply_start('Dağıtım & kanal merkezi',$active_module);?>
<section class="page-intro"><p>OTA, acente, doğrudan satış ve metasearch dağıtımını tek merkezden yönetin. Her bağlantıda stok, fiyat, kısıt ve rezervasyon akışının sahibini ayrı ayrı seçin.</p></section><?php if($message):?><p class="save-success">✓ <?=htmlspecialchars($message)?></p><?php endif;?><?php if($error):?><p class="login-error"><?=htmlspecialchars($error)?></p><?php endif;?>
<section class="next-module"><h2>1. Kanal bağlantısı ve ARI yetkileri</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="connection"><div class="form-row"><label>Kanal kodu<input name="channel_code" placeholder="booking_com" required></label><label>Görünen ad<input name="display_name" placeholder="Booking.com" required></label><label>Kanal tesis kodu<input name="property_code" placeholder="Örn. 123456"></label></div><fieldset><legend>NEXUS’un yöneteceği akışlar</legend><label><input type="checkbox" name="availability" checked> Kontenjan</label><label><input type="checkbox" name="rates" checked> Fiyat</label><label><input type="checkbox" name="restrictions" checked> Kısıtlar</label><label><input type="checkbox" name="reservations" checked> Rezervasyon alımı</label></fieldset><button>Bağlantı taslağını kaydet</button></form><?php foreach($connections as $c):$s=json_decode($c['sync_scopes']??'{}',true)?:[];?><article class="conn-block"><p><b><?=htmlspecialchars($c['display_name'])?></b> · <?=htmlspecialchars($c['status'])?> · <?=implode(', ',array_keys(array_filter($s)))?:'akış seçilmedi'?> · son durum: <?=htmlspecialchars($c['last_sync_status'])?></p><div class="ical-url-box"><span class="ical-url-label" title="https://nexustraveltech.com/api/channel-webhook?token=<?=htmlspecialchars($c['access_token'])?>">api/channel-webhook?token=<?=htmlspecialchars(substr($c['access_token'],0,10))?>…<?=htmlspecialchars(substr($c['access_token'],-4))?></span><button type="button" class="ical-copy-btn" data-copy="https://nexustraveltech.com/api/channel-webhook?token=<?=htmlspecialchars($c['access_token'])?>">Kopyala</button></div><p class="conn-hint">Kanal tarafına bildirimler için bu webhook adresini verin. Bağlantı aktif olduğunda gönderilen JSON bildirimleri işlem günlüğünde görünür.</p></article><?php endforeach;?></section>
<section class="next-module"><h2>2. Ürün eşleştirmesi</h2><p>Bağlantı aktifleştirilmeden önce NEXUS ürününüzü kanalın tesis koduna bağlayın. Sonraki adımda oda ve fiyat planı eşleştirmeleri bu karta eklenir.</p><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="property_map"><div class="form-row"><label>Kanal<select name="connection_id"><?php foreach($connections as $c):?><option value="<?=$c['id']?>"><?=htmlspecialchars($c['display_name'])?></option><?php endforeach;?></select></label><label>NEXUS ürünü<select name="property_id"><?php foreach($properties as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['name'])?></option><?php endforeach;?></select></label><label>Kanal ürün kodu<input name="external_property_id" required></label></div><button>Eşleştirmeyi kaydet</button></form><?php foreach($mappings as $m):?><p><b><?=htmlspecialchars($m['display_name'])?></b> · <?=htmlspecialchars($m['property_name'])?> → <?=htmlspecialchars($m['external_property_id'])?></p><?php endforeach;?></section>
<section class="next-module"><h2>3. Gönderim kuyruğu & işlem günlüğü</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="queue"><div class="form-row"><label>Kanal<select name="connection_id"><?php foreach($connections as $c):?><option value="<?=$c['id']?>"><?=htmlspecialchars($c['display_name'])?></option><?php endforeach;?></select></label><label>Gönderim türü<select name="scope"><option value="availability">Kontenjan</option><option value="rates">Fiyat</option><option value="restrictions">Kısıtlar</option><option value="content">İlan içeriği</option></select></label></div><button>Manuel senkronizasyon başlat</button></form><?php foreach($logs as $log):?><p><b><?=htmlspecialchars($log['display_name'])?></b> · <?=htmlspecialchars($log['direction'])?> / <?=htmlspecialchars($log['scope'])?> · <strong><?=htmlspecialchars($log['status'])?></strong> · <?=htmlspecialchars($log['created_at'])?> <?= $log['error_message']?'· '.htmlspecialchars($log['error_message']):''?></p><?php endforeach;?></section><script>function fallbackCopy(text){var ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy')}catch(e){}document.body.removeChild(ta)}document.querySelectorAll('.ical-copy-btn').forEach(function(b){b.addEventListener('click',function(){var url=this.getAttribute('data-copy'),btn=this;function done(){btn.textContent='Kopyalandı ✓';btn.classList.add('copied');setTimeout(function(){btn.textContent='Kopyala';btn.classList.remove('copied')},1600)}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(url).then(done).catch(function(){fallbackCopy(url);done()})}else{fallbackCopy(url);done()}})});</script><?php supply_end();
