<?php
require_once __DIR__ . '/../config/supplier_auth.php';
$supplier_user = require_supplier();
$active_module = $active_module ?? 'dashboard';
function supply_start(string $title, string $active): void { ?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?> | NEXUS Supply</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/nexustraveltech/assets/supply.css"></head><body><div class="supply-app"><aside class="side"><a class="supply-brand" href="/nexustraveltech/">N<span>∿</span>XUS <small>SUPPLY</small></a><nav>
<?php $links=['dashboard'=>['','Genel bakış'],'verification'=>['hesap-dogrulama','Hesap doğrulama'],'properties'=>['tesisler','Tesisler & ürünler'],'inventory'=>['fiyat-kontenjan','Fiyat & kontenjan'],'rate_rules'=>['satis-kurallari','Satış kuralları'],'distribution'=>['dagitim-merkezi','Dağıtım & kanallar'],'ical'=>['ical-takvimler','iCal takvimler'],'hotel_ops'=>['otel-operasyon','Otel ön büro'],'room_rack'=>['otel-room-rack','Room Rack & gruplar'],'hotel_team'=>['otel-ekip-hizmet','Kat hizmetleri & servis'],'hotel_control'=>['otel-kontrol','Otel kontrol & gün sonu'],'hotel_finance'=>['otel-finans','Finans & night audit'],'hotel_revenue'=>['otel-gelir-crm','Gelir, CRM & sadakat'],'agency_requests'=>['acente-talepleri','Acente talepleri'],'bookings'=>['rezervasyonlar','Rezervasyonlar'],'payments'=>['odeme-ayarlari','Tahsilat & POS'],'invoices'=>['faturalama','Muhasebe & fatura'],'ai'=>['yapay-zeka','NEXUS AI']]; foreach($links as $key=>[$path,$label]): ?><a class="<?=$active===$key?'active':''?>" href="/nexustraveltech/tedarikci/<?=$path?>"><?=htmlspecialchars($label)?></a><?php endforeach; ?>
</nav><div class="side-foot"><a class="<?=$active==='hotel_guest_crm'?'active':''?>" href="/nexustraveltech/tedarikci/otel-misafir-crm">Misafir CRM</a><a class="<?=$active==='hotel_staff'?'active':''?>" href="/nexustraveltech/tedarikci/otel-personel">Personel & roller</a><a class="<?=$active==='hotel_mobile'?'active':''?>" href="/nexustraveltech/tedarikci/kat-hizmetleri-mobil">Mobil kat hizmetleri</a><span>PİLOT ORTAM</span><a href="/nexustraveltech/tedarikci/logout">Güvenli çıkış</a></div></aside><main class="supply-main"><header class="supply-top"><div><span class="crumb">NEXUS SUPPLY / <?=strtoupper(htmlspecialchars($active))?></span><h1><?=htmlspecialchars($title)?></h1></div><div class="user-chip"><b><?=htmlspecialchars($GLOBALS['supplier_user']['full_name'])?></b><span><?=htmlspecialchars($GLOBALS['supplier_user']['role'])?></span></div></header>
<?php }
function supply_end(): void { ?></main></div></body></html><?php }
