<?php
$active_module='payments'; require_once __DIR__.'/layout.php';
$u=$supplier_user; $pdo=db(); $error=''; $notice=isset($_GET['saved'])?'Tahsilat ayarları kaydedildi. Sanal POS başvurusu inceleme aşamasına alındı.':'';
$q=$pdo->prepare('SELECT * FROM supplier_payment_settings WHERE supplier_id=?');$q->execute([$u['supplier_id']]);$settings=$q->fetch() ?: ['virtual_pos_enabled'=>0,'provider_name'=>'','merchant_name'=>'','settlement_iban'=>'','installment_enabled'=>0,'installment_max'=>'','pos_status'=>'draft'];
if($_SERVER['REQUEST_METHOD']==='POST'){
  $enabled=isset($_POST['virtual_pos_enabled'])?1:0;$provider=trim((string)($_POST['provider_name']??''));$merchant=trim((string)($_POST['merchant_name']??''));$iban=preg_replace('/\s+/','',strtoupper(trim((string)($_POST['settlement_iban']??''))));$installment=isset($_POST['installment_enabled'])?1:0;$max=$installment?max(2,min(18,(int)($_POST['installment_max']??2))):null;
  if($enabled && ($merchant==='' || !preg_match('/^TR\d{24}$/',$iban))) $error='Sanal POS başvurusu için üye işyeri ünvanı ve geçerli Türkiye IBAN’ı gereklidir.';
  else { $status=$enabled?'review':'draft';$stmt=$pdo->prepare('INSERT INTO supplier_payment_settings (supplier_id,virtual_pos_enabled,provider_name,merchant_name,settlement_iban,installment_enabled,installment_max,pos_status) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT (supplier_id) DO UPDATE SET virtual_pos_enabled=EXCLUDED.virtual_pos_enabled,provider_name=EXCLUDED.provider_name,merchant_name=EXCLUDED.merchant_name,settlement_iban=EXCLUDED.settlement_iban,installment_enabled=EXCLUDED.installment_enabled,installment_max=EXCLUDED.installment_max,pos_status=EXCLUDED.pos_status,updated_at=now()');$stmt->execute([$u['supplier_id'],$enabled,$provider?:null,$merchant?:null,$iban?:null,$installment,$max,$status]);header('Location: /nexustraveltech/tedarikci/odeme-ayarlari?saved=1');exit; }
}
supply_start('Tahsilat & sanal POS', $active_module); ?>
<section class="payment-hero"><div><span>İSTEĞE BAĞLI TAHSİLAT ALTYAPISI</span><h2>Rezervasyon bedelini<br>kendi hesabınıza alın.</h2><p>NEXUS; otel sahibinin talebiyle sanal POS ve ödeme akışını bağlayacak altyapıyı sunar. Kart bilgileri NEXUS’ta saklanmaz; seçilen ödeme kuruluşunun güvenli ödeme sayfası kullanılır.</p></div><div class="pos-status"><span>DURUM</span><b><?= $settings['pos_status']==='active'?'Aktif':($settings['pos_status']==='review'?'İnceleme bekliyor':'Kurulum bekliyor') ?></b><p>Canlı tahsilat, sözleşmeli ödeme kuruluşu ve doğrulanmış üye işyeri hesabı sonrasında açılır.</p></div></section>
<?php if($error): ?><p class="login-error"><?= htmlspecialchars($error) ?></p><?php endif; ?><?php if($notice): ?><p class="save-success">✓ <?= htmlspecialchars($notice) ?></p><?php endif; ?>
<form method="post" class="payment-form"><section><h3>Sanal POS tercihi</h3><label class="toggle-row"><input type="checkbox" name="virtual_pos_enabled" <?= $settings['virtual_pos_enabled']?'checked':'' ?>><span><b>Sanal POS başvurusu oluştur</b><small>Oteliniz, kendi üye işyeri hesabı üzerinden kartlı ödeme almak istiyor.</small></span></label><label>Ödeme kuruluşu / banka (varsa)<input name="provider_name" value="<?= htmlspecialchars($settings['provider_name']??'') ?>" placeholder="Örn. Banka veya ödeme kuruluşu adı"></label><label>Üye işyeri ünvanı<input name="merchant_name" value="<?= htmlspecialchars($settings['merchant_name']??'') ?>" placeholder="Faturadaki yasal ünvan"></label><label>Ödeme aktarım IBAN’ı<input name="settlement_iban" value="<?= htmlspecialchars($settings['settlement_iban']??'') ?>" maxlength="34" autocomplete="off" placeholder="TR00 0000 0000 0000 0000 0000 00"></label><label class="toggle-row"><input type="checkbox" name="installment_enabled" <?= $settings['installment_enabled']?'checked':'' ?>><span><b>Taksit seçeneği sun</b><small>Yasal ve banka kuralları kapsamında kart taksitlerini etkinleştirmek için.</small></span></label><label>Maksimum taksit sayısı<select name="installment_max"><?php for($i=2;$i<=18;$i++): ?><option value="<?= $i ?>" <?= (int)$settings['installment_max']===$i?'selected':'' ?>><?= $i ?> taksit</option><?php endfor; ?></select></label></section><aside><h3>Ödeme akışı</h3><ol><li>Acente veya son kullanıcı güvenli ödeme bağlantısına yönlenir.</li><li>Ödeme kuruluşu 3D Secure doğrulamasını yürütür.</li><li>Başarılı tahsilat rezervasyon ve muhasebe kaydına işlenir.</li><li>Mutabakat, tedarikçinin doğrulanmış hesabına göre ilerler.</li></ol><p><b>Not:</b> Kart numarası, CVV veya ödeme kuruluşu gizli anahtarını bu ekrana girmeyin.</p></aside><div class="form-actions"><a href="/nexustraveltech/tedarikci/">İptal</a><button type="submit">Tahsilat ayarlarını kaydet →</button></div></form><?php supply_end(); ?>
