<?php
declare(strict_types=1);
$active_module='hotel_guest_crm'; require_once __DIR__.'/layout.php';
if(empty($_SESSION['supplier_csrf']))$_SESSION['supplier_csrf']=bin2hex(random_bytes(32));
$u=$supplier_user;$pdo=db();$message='';$error='';
try { if($_SERVER['REQUEST_METHOD']==='POST') { if(!hash_equals($_SESSION['supplier_csrf'],(string)($_POST['csrf']??'')))throw new RuntimeException('Güvenlik doğrulaması geçersiz.'); $action=$_POST['action']??'';
 if($action==='segment') {$pdo->prepare('INSERT INTO guest_segments(supplier_id,name,criteria,is_active) VALUES(?,?,?::jsonb,true)')->execute([$u['supplier_id'],trim((string)$_POST['name']),json_encode(['note'=>trim((string)$_POST['criteria'])],JSON_UNESCAPED_UNICODE)]);$message='Misafir segmenti oluşturuldu.';}
 if($action==='communication') {$guest=(int)$_POST['guest_id'];$q=$pdo->prepare('SELECT id FROM guest_profiles WHERE id=? AND supplier_id=?');$q->execute([$guest,$u['supplier_id']]);if(!$q->fetch())throw new RuntimeException('Misafir bulunamadı.');$pdo->prepare("INSERT INTO guest_communications(supplier_id,guest_id,channel,subject,body,status,scheduled_at,sent_at) VALUES(?,?,?,?,?,'sent',now(),now())")->execute([$u['supplier_id'],$guest,$_POST['channel']??'email',trim((string)$_POST['subject']),trim((string)$_POST['body'])]);$message='İletişim kaydı işlendi.';}
 if($action==='service_request') {$guest=(int)$_POST['guest_id'];$pdo->prepare("INSERT INTO guest_service_requests(supplier_id,guest_id,property_id,request_type,details,priority,status) VALUES(?,?,?,?,?,?, 'open')")->execute([$u['supplier_id'],$guest,(int)$_POST['property_id']?:null,$_POST['request_type']??'other',trim((string)$_POST['details']),$_POST['priority']??'normal']);$message='Misafir talebi kaydedildi.';}
 if($action==='request_status') {$pdo->prepare("UPDATE guest_service_requests SET status=?,resolved_at=CASE WHEN ? IN ('resolved','cancelled') THEN now() ELSE NULL END WHERE id=? AND supplier_id=?")->execute([$_POST['status'],$_POST['status'],(int)$_POST['id'],$u['supplier_id']]);$message='Talep durumu güncellendi.';}
 }} catch(Throwable $e){$error=$e->getMessage();}
$q=$pdo->prepare("SELECT g.*,COUNT(DISTINCT bg.booking_id) stays,MAX(b.check_out) last_stay FROM guest_profiles g LEFT JOIN booking_guests bg ON bg.guest_id=g.id LEFT JOIN supplier_bookings b ON b.id=bg.booking_id WHERE g.supplier_id=? GROUP BY g.id ORDER BY last_stay DESC NULLS LAST,g.id DESC LIMIT 150");$q->execute([$u['supplier_id']]);$guests=$q->fetchAll();
$q=$pdo->prepare("SELECT id,name FROM properties WHERE supplier_id=? AND property_type='hotel' ORDER BY name");$q->execute([$u['supplier_id']]);$hotels=$q->fetchAll();
$q=$pdo->prepare('SELECT * FROM guest_segments WHERE supplier_id=? ORDER BY id DESC');$q->execute([$u['supplier_id']]);$segments=$q->fetchAll();
$q=$pdo->prepare("SELECT r.*,g.first_name,g.last_name,p.name property_name FROM guest_service_requests r JOIN guest_profiles g ON g.id=r.guest_id LEFT JOIN properties p ON p.id=r.property_id WHERE r.supplier_id=? ORDER BY CASE WHEN r.status='open' THEN 0 ELSE 1 END,r.created_at DESC LIMIT 100");$q->execute([$u['supplier_id']]);$requests=$q->fetchAll();
supply_start('Misafir CRM ve hizmet talepleri',$active_module); ?>
<section class="page-intro"><p>Konaklama geçmişi, tercih ve pazarlama izniyle misafiri tanıyın; servis taleplerini kayıt altına alıp kapatın. İletişim ekranı yalnızca açık onay bulunan misafirler için kullanılmalıdır.</p></section><?php if($message):?><p class="save-success">✓ <?=htmlspecialchars($message)?></p><?php endif;?><?php if($error):?><p class="login-error"><?=htmlspecialchars($error)?></p><?php endif;?>
<section class="next-module"><h2>Segment tanımı</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="segment"><div class="form-row"><input name="name" required placeholder="Örn. Aile tatili / yüksek değerli misafir"><input name="criteria" placeholder="Segment kuralı veya açıklaması"></div><button>Segmenti kaydet</button></form><?php foreach($segments as $s): $criteria=json_decode((string)$s['criteria'],true)?:[];?><p><b><?=htmlspecialchars($s['name'])?></b> · <?=htmlspecialchars($criteria['note']??'')?></p><?php endforeach;?></section>
<section class="next-module"><h2>Misafir iletişimi ve hizmet talebi</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="communication"><div class="form-row"><select name="guest_id"><?php foreach($guests as $g):?><option value="<?=$g['id']?>"><?=htmlspecialchars($g['first_name'].' '.$g['last_name'].' · '.$g['email'])?></option><?php endforeach;?></select><select name="channel"><option value="email">E-posta</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="phone">Telefon</option></select><input name="subject" required placeholder="Konu"></div><textarea name="body" required placeholder="İletişim özeti veya gönderilen mesaj"></textarea><button>İletişim kaydı ekle</button></form><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="service_request"><div class="form-row"><select name="guest_id"><?php foreach($guests as $g):?><option value="<?=$g['id']?>"><?=htmlspecialchars($g['first_name'].' '.$g['last_name'])?></option><?php endforeach;?></select><select name="property_id"><option value="">Otel dışı</option><?php foreach($hotels as $h):?><option value="<?=$h['id']?>"><?=htmlspecialchars($h['name'])?></option><?php endforeach;?></select><select name="request_type"><option value="housekeeping">Kat hizmetleri</option><option value="maintenance">Teknik servis</option><option value="restaurant">Restoran</option><option value="transfer">Transfer</option><option value="other">Diğer</option></select><select name="priority"><option value="normal">Normal</option><option value="high">Yüksek</option><option value="urgent">Acil</option></select></div><textarea name="details" required placeholder="Talep detayı"></textarea><button>Talebi aç</button></form></section>
<section class="next-module"><h2>Açık talepler</h2><?php foreach($requests as $r):?><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="request_status"><input type="hidden" name="id" value="<?=$r['id']?>"><b><?=htmlspecialchars($r['first_name'].' '.$r['last_name'])?></b> · <?=htmlspecialchars($r['request_type'])?> · <?=htmlspecialchars($r['details'])?> <select name="status"><option><?=$r['status']?></option><option value="in_progress">in_progress</option><option value="resolved">resolved</option><option value="cancelled">cancelled</option></select><button>Güncelle</button></form><?php endforeach;?></section>
<section class="next-module"><h2>Misafir görünümü</h2><?php foreach($guests as $g):?><p><b><?=htmlspecialchars($g['first_name'].' '.$g['last_name'])?></b> · <?=htmlspecialchars($g['email']??$g['phone']??'İletişim yok')?> · <?= (int)$g['stays']?> konaklama · son çıkış <?=htmlspecialchars($g['last_stay']??'-')?> · pazarlama izni <?= $g['marketing_consent']?'var':'yok'?></p><?php endforeach;?></section>
<?php supply_end();
