<?php
$active_module = 'properties'; require_once __DIR__ . '/layout.php'; require_once __DIR__ . '/../config/hotel_form.php';
$u=$supplier_user; $id=filter_input(INPUT_GET,'product',FILTER_VALIDATE_INT); if(!$id){header('Location: /nexustraveltech/tedarikci/tesisler');exit;}
$q=db()->prepare("SELECT * FROM properties WHERE id=? AND supplier_id=? AND property_type='hotel'");$q->execute([$id,$u['supplier_id']]);$hotel=$q->fetch();if(!$hotel){http_response_code(404);exit('Otel bulunamadı.');}
$locales=['en'=>'English','de'=>'Deutsch','ru'=>'Русский','ar'=>'العربية','fr'=>'Français']; $scopes=['property'=>'Genel tesis','room'=>'Oda','bathroom'=>'Banyo','activity'=>'Aktivite','event'=>'Etkinlik','kids_club'=>'Çocuk kulübü']; $error='';$notice=isset($_GET['saved'])?'Medya kaydedildi.':(isset($_GET['translated'])?'AI çevirileri kaydedildi.':'');
function translation_upsert(int $propertyId,string $entityType,int $entityId,string $locale,string $field,string $value):void{db()->prepare('INSERT INTO property_content_translations (property_id,entity_type,entity_id,locale,field_key,value,translation_source) VALUES (?,?,?,?,?,?,?) ON CONFLICT (property_id,entity_type,entity_id,locale,field_key) DO UPDATE SET value=EXCLUDED.value,translation_source=EXCLUDED.translation_source,updated_at=now()')->execute([$propertyId,$entityType,$entityId,$locale,$field,$value,'ai']);}
function ai_translate_nexus(string $text,string $locale):string{
  $settings=db_config();$key=(string)($settings['deepseek_api_key']??'');
  if($key==='')throw new RuntimeException('AI çevirisi için config/secrets.php içine deepseek_api_key eklenmelidir.');
  $language=['en'=>'English','de'=>'German','ru'=>'Russian','ar'=>'Arabic','fr'=>'French'][$locale]??$locale;
  $body=['model'=>$settings['deepseek_model']??'deepseek-chat','messages'=>[
    ['role'=>'system','content'=>'You translate tourism listing content accurately. Return only the requested translation.'],
    ['role'=>'user','content'=>"Translate the following Turkish tourism listing text into {$language}. Keep proper names, numbers, concise sales tone and HTML-free formatting.\n\n".$text]
  ],'stream'=>false,'temperature'=>0.2];
  $ch=curl_init('https://api.deepseek.com/chat/completions');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$key],CURLOPT_POSTFIELDS=>json_encode($body,JSON_UNESCAPED_UNICODE),CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>45]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$data=json_decode((string)$raw,true);
  if($status<200||$status>=300||empty($data['choices'][0]['message']['content']))throw new RuntimeException('DeepSeek çevirisi tamamlanamadı.');
  return trim($data['choices'][0]['message']['content']);
}
$rooms=db()->prepare('SELECT id,name FROM room_types WHERE property_id=? ORDER BY id');$rooms->execute([$id]);$rooms=$rooms->fetchAll();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if (!csrf_valid($_POST['csrf_token'] ?? null)) { $error = 'Güvenlik doğrulaması yenilendi. Lütfen tekrar deneyin.'; }
  elseif (($_POST['action'] ?? '') === 'upload_media') {
    $scope = $_POST['media_scope'] ?? 'property'; $roomId = (int)($_POST['room_type_id'] ?? 0);
    if (!in_array($scope, array_keys($scopes), true)) $error = 'Geçerli medya türü seçin.';
    if ($error === '' && in_array($scope, ['room','bathroom'], true)) { $check=db()->prepare('SELECT 1 FROM room_types WHERE id=? AND property_id=?'); $check->execute([$roomId,$id]); if (!$check->fetch()) $error='Oda veya banyo görseli için ilgili oda tipini seçin.'; }
    if (!in_array($scope, ['room','bathroom'], true)) $roomId = 0;
    $file = $_FILES['media'] ?? null; $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
    if ($error === '' && (!$file || $file['error'] !== UPLOAD_ERR_OK || $file['size'] > 8*1024*1024)) $error='JPG, PNG veya WEBP biçiminde en fazla 8 MB görsel yükleyin.';
    if ($error === '') { $mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']); if(!isset($allowed[$mime])) $error='Bu görsel biçimi desteklenmiyor.'; else { $dir=dirname(__DIR__).'/uploads/properties/'.$id; if(!is_dir($dir)) mkdir($dir,0755,true); $filename=bin2hex(random_bytes(12)).'.'.$allowed[$mime]; if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$filename)) $error='Görsel yüklenemedi.'; else { db()->prepare('INSERT INTO property_media (property_id,room_type_id,media_scope,file_path,file_name,mime_type,title,description,alt_text,is_cover,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$roomId?:null,$scope,'uploads/properties/'.$id.'/'.$filename,basename((string)$file['name']),$mime,trim((string)($_POST['title']??''))?:null,trim((string)($_POST['description']??''))?:null,trim((string)($_POST['alt_text']??''))?:null,false,0]); header('Location: /nexustraveltech/tedarikci/otel-icerik-medya?product='.$id.'&saved=1'); exit; } } }
  } elseif (($_POST['action'] ?? '') === 'translate_all') {
    $targets=array_values(array_intersect($_POST['locales']??[],array_keys($locales))); if(!$targets) $error='En az bir hedef dil seçin.'; else try { $details=json_decode($hotel['product_details']??'{}',true)?:[]; $items=[['property',0,'name',$hotel['name']],['property',0,'short_description',$details['short_description']??''],['property',0,'description',$details['description']??'']]; $m=db()->prepare('SELECT id,title,description,alt_text FROM property_media WHERE property_id=?');$m->execute([$id]); foreach($m->fetchAll() as $media) foreach(['title','description','alt_text'] as $field) $items[]=['media',(int)$media['id'],$field,$media[$field]??'']; foreach($targets as $locale) foreach($items as [$type,$entity,$field,$value]) if(trim((string)$value)!=='') translation_upsert($id,$type,$entity,$locale,$field,ai_translate_nexus($value,$locale)); header('Location: /nexustraveltech/tedarikci/otel-icerik-medya?product='.$id.'&translated=1'); exit; } catch(Throwable $e) { $error=$e->getMessage(); }
  }
}
$m=db()->prepare('SELECT pm.*,r.name room_name FROM property_media pm LEFT JOIN room_types r ON r.id=pm.room_type_id WHERE pm.property_id=? ORDER BY pm.media_scope,pm.id DESC');$m->execute([$id]);$media=$m->fetchAll();
supply_start(htmlspecialchars($hotel['name']).' · içerik ve görseller',$active_module); ?>
<section class="page-intro"><p>Genel tesis, oda, banyo, aktivite, etkinlik ve çocuk kulübü görsellerini ayrı ekleyin. Türkçe içerikler tek seferde seçtiğiniz dillere AI ile çevrilir.</p></section><?php if($error):?><p class="login-error"><?=htmlspecialchars($error)?></p><?php endif;?><?php if($notice):?><p class="save-success">✓ <?=htmlspecialchars($notice)?></p><?php endif;?>
<style>.media-panel{background:#fff;border:1px solid var(--line);border-radius:10px;padding:25px;margin:14px 0}.media-panel h2{margin:0 0 8px;font-size:20px}.media-panel p{color:var(--muted);font-size:13px;line-height:1.5}.media-form{display:grid;grid-template-columns:1fr 1fr;gap:13px}.media-form label{display:grid;gap:6px;font-size:12px;font-weight:700}.media-form input,.media-form select,.media-form textarea{border:1px solid var(--line);border-radius:6px;padding:10px;font:inherit}.media-form .wide{grid-column:1/-1}.media-form button,.ai-button{border:0;border-radius:6px;background:var(--navy);color:#fff;padding:12px 15px;font-weight:700;width:max-content}.media-groups{display:grid;gap:14px}.media-group{background:#fff;border:1px solid var(--line);border-radius:8px;padding:18px}.media-group h3{margin:0 0 12px;font-size:15px}.media-cards{display:flex;flex-wrap:wrap;gap:10px}.media-card{width:150px}.media-card img{display:block;width:150px;height:96px;object-fit:cover;border-radius:5px}.media-card b,.media-card span{display:block;font-size:11px;margin-top:5px}.media-card span{color:var(--muted)}.locale-list{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}.locale-list label{border:1px solid var(--line);padding:8px;border-radius:5px;font-size:12px}@media(max-width:620px){.media-form{grid-template-columns:1fr}}</style>
<section class="media-panel"><h2>AI ile çoklu dil çevirisi</h2><p>Otel adı, genel açıklamalar ve tüm görsel başlık/açıklama/alt metinleri seçili dillere kaydedilir. Önce Türkçe içerikleri tamamlayın.</p><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="translate_all"><div class="locale-list"><?php foreach($locales as $key=>$label):?><label><input type="checkbox" name="locales[]" value="<?=$key?>"> <?=htmlspecialchars($label)?></label><?php endforeach;?></div><button class="ai-button">Seçilen dillere AI ile çevir →</button></form></section>
<section class="media-panel"><h2>Görsel ekle</h2><form method="post" enctype="multipart/form-data" class="media-form"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="upload_media"><label>Görsel türü<select name="media_scope"><?php foreach($scopes as $key=>$label):?><option value="<?=$key?>"><?=htmlspecialchars($label)?></option><?php endforeach;?></select></label><label>Bağlı oda tipi <select name="room_type_id"><option value="">Yalnızca oda/banyo için seçin</option><?php foreach($rooms as $room):?><option value="<?= (int)$room['id']?>"><?=htmlspecialchars($room['name'])?></option><?php endforeach;?></select></label><label class="wide">Dosya<input type="file" name="media" accept="image/jpeg,image/png,image/webp" required></label><label>Türkçe başlık<input name="title" maxlength="190" placeholder="Örn. Deluxe oda yatak alanı"></label><label>Türkçe alt metin<input name="alt_text" maxlength="255" placeholder="Erişilebilirlik ve SEO açıklaması"></label><label class="wide">Türkçe açıklama<textarea name="description" rows="3" placeholder="Bu görseldeki deneyimi anlatın; AI diğer dillere çevirebilir."></textarea></label><button>Görseli kaydet →</button></form></section>
<section class="media-groups"><?php foreach($scopes as $scope=>$label):$group=array_filter($media,fn($item)=>$item['media_scope']===$scope);if(!$group)continue;?><article class="media-group"><h3><?=htmlspecialchars($label)?></h3><div class="media-cards"><?php foreach($group as $item):?><div class="media-card"><img src="/uploads/properties/<?= (int)$id ?>/<?=htmlspecialchars(basename($item['file_path']))?>" alt="<?=htmlspecialchars($item['alt_text']?:$item['title']?:$hotel['name'])?>"><b><?=htmlspecialchars($item['title']?:'Başlıksız görsel')?></b><span><?=htmlspecialchars($item['room_name']?:'Genel')?></span></div><?php endforeach;?></div></article><?php endforeach;?></section><?php supply_end(); ?>
