<?php
declare(strict_types=1);
$active_module='hotel_guest_crm'; require_once __DIR__.'/layout.php';
if(empty($_SESSION['supplier_csrf']))$_SESSION['supplier_csrf']=bin2hex(random_bytes(32));
$u=$supplier_user;$pdo=db();$message='';$error='';
try { if($_SERVER['REQUEST_METHOD']==='POST') { if(!hash_equals($_SESSION['supplier_csrf'],(string)($_POST['csrf']??'')))throw new RuntimeException('Güvenlik doğrulaması geçersiz.'); $action=$_POST['action']??'';
 if($action==='segment') {$pdo->prepare('INSERT INTO guest_segments(supplier_id,name,criteria,is_active) VALUES(?,?,?::jsonb,true)')->execute([$u['supplier_id'],trim((string)$_POST['name']),json_encode(['note'=>trim((string)$_POST['criteria'])],JSON_UNESCAPED_UNICODE)]);$message='Misafir segmenti oluşturuldu.';}
 if($action==='communication') {$guest=(int)$_POST['guest_id'];$q=$pdo->prepare('SELECT id FROM guest_profiles WHERE id=? AND supplier_id=?');$q->execute([$guest,$u['supplier_id']]);if(!$q->fetch())throw new RuntimeException('Misafir bulunamadı.');$pdo->prepare("INSERT INTO guest_communications(supplier_id,guest_id,channel,subject,body,status,scheduled_at,sent_at) VALUES(?,?,?,?,?,'sent',now(),now())")->execute([$u['supplier_id'],$guest,$_POST['channel']??'email',trim((string)$_POST['subject']),trim((string)$_POST['body'])]);$message='İletişim kaydı işlendi.';}
 if($action==='service_request') {$guest=(int)$_POST['guest_id'];$q=$pdo->prepare('SELECT id FROM guest_profiles WHERE id=? AND supplier_id=?');$q->execute([$guest,$u['supplier_id']]);if(!$q->fetch())throw new RuntimeException('Misafir bulunamadı.');$pdo->prepare("INSERT INTO guest_service_requests(booking_id,guest_id,request_type,details,priority,status) VALUES(?,?,?,?,?, 'open')")->execute([(int)$_POST['booking_id']?:null,$guest,$_POST['request_type']??'other',trim((string)$_POST['details']),$_POST['priority']??'normal']);$message='Misafir talebi kaydedildi.';}
 if($action==='request_status') {$pdo->prepare("UPDATE guest_service_requests SET status=?,resolved_at=CASE WHEN ? IN ('resolved','cancelled') THEN now() ELSE NULL END WHERE id=? AND guest_id IN (SELECT id FROM guest_profiles WHERE supplier_id=?)")->execute([$_POST['status'],$_POST['status'],(int)$_POST['id'],$u['supplier_id']]);$message='Talep durumu güncellendi.';}
 if($action==='redeem') {require_once __DIR__.'/../config/loyalty.php';$guest=(int)$_POST['guest_id'];$q=$pdo->prepare('SELECT la.id FROM guest_loyalty_accounts la JOIN guest_profiles g ON g.id=la.guest_id WHERE la.guest_id=? AND g.supplier_id=?');$q->execute([$guest,$u['supplier_id']]);$accountId=(int)$q->fetchColumn();if(!$accountId)throw new RuntimeException('Sadakat hesabı yok.');$r=redeem_loyalty_points($accountId,(int)$_POST['folio_id'],(float)str_replace(',','.',(string)$_POST['points']));$message='Puan kullanıldı: '.$r['credit'].' EUR folyo kredisi eklendi.';}
 }} catch(Throwable $e){$error=$e->getMessage();}
$q=$pdo->prepare("SELECT g.*,la.points_balance,la.lifetime_nights,la.lifetime_revenue,t.name tier_name,COUNT(DISTINCT bg.booking_id) stays,MAX(b.check_out) last_stay,(SELECT ROUND(AVG(r.rating),1) FROM guest_reviews r WHERE r.booking_id IN (SELECT bg2.booking_id FROM booking_guests bg2 WHERE bg2.guest_id=g.id) AND r.status='published') avg_rating FROM guest_profiles g LEFT JOIN guest_loyalty_accounts la ON la.guest_id=g.id LEFT JOIN loyalty_tiers t ON t.id=la.tier_id LEFT JOIN booking_guests bg ON bg.guest_id=g.id LEFT JOIN supplier_bookings b ON b.id=bg.booking_id WHERE g.supplier_id=? GROUP BY g.id,la.points_balance,la.lifetime_nights,la.lifetime_revenue,t.name ORDER BY last_stay DESC NULLS LAST,g.id DESC LIMIT 150");$q->execute([$u['supplier_id']]);$guests=$q->fetchAll();
$detail=null;$ledger=[];$stays=[];$reviews=[];$openFolios=[];
$guestId=(int)($_GET['guest']??0);
if($guestId){$q=$pdo->prepare('SELECT * FROM guest_profiles WHERE id=? AND supplier_id=?');$q->execute([$guestId,$u['supplier_id']]);$detail=$q->fetch()?:null;
 if($detail){$q=$pdo->prepare('SELECT la.*,t.name tier_name FROM guest_loyalty_accounts la LEFT JOIN loyalty_tiers t ON t.id=la.tier_id WHERE la.guest_id=?');$q->execute([$guestId]);$loyalty=$q->fetch()?:null;
  if($loyalty){$q=$pdo->prepare('SELECT * FROM loyalty_ledger WHERE account_id=? ORDER BY id DESC LIMIT 30');$q->execute([$loyalty['id']]);$ledger=$q->fetchAll();}
  $q=$pdo->prepare("SELECT b.booking_reference,b.booking_status,b.check_in,b.check_out,b.total_amount,b.currency,b.deposit_amount,b.deposit_status,p.name property_name FROM supplier_bookings b JOIN booking_guests bg ON bg.booking_id=b.id LEFT JOIN properties p ON p.id=b.property_id WHERE bg.guest_id=? ORDER BY b.check_in DESC");$q->execute([$guestId]);$stays=$q->fetchAll();
  $q=$pdo->prepare("SELECT r.*,p.name property_name FROM guest_reviews r JOIN booking_guests bg ON bg.booking_id=r.booking_id LEFT JOIN properties p ON p.id=r.property_id WHERE bg.guest_id=? ORDER BY r.created_at DESC");$q->execute([$guestId]);$reviews=$q->fetchAll();
  $q=$pdo->prepare("SELECT bf.id,bf.currency,b.booking_reference FROM booking_folios bf JOIN supplier_bookings b ON b.id=bf.booking_id JOIN booking_guests bg ON bg.booking_id=b.id WHERE bg.guest_id=? AND bf.status='open' ORDER BY bf.id");$q->execute([$guestId]);$openFolios=$q->fetchAll();}
}
$q=$pdo->prepare("SELECT id,name FROM properties WHERE supplier_id=? AND property_type='hotel' ORDER BY name");$q->execute([$u['supplier_id']]);$hotels=$q->fetchAll();
$q=$pdo->prepare('SELECT * FROM guest_segments WHERE supplier_id=? ORDER BY id DESC');$q->execute([$u['supplier_id']]);$segments=$q->fetchAll();
$q=$pdo->prepare("SELECT r.*,g.first_name,g.last_name FROM guest_service_requests r JOIN guest_profiles g ON g.id=r.guest_id WHERE g.supplier_id=? ORDER BY CASE WHEN r.status='open' THEN 0 ELSE 1 END,r.created_at DESC LIMIT 100");$q->execute([$u['supplier_id']]);$requests=$q->fetchAll();
supply_start('Misafir CRM ve hizmet talepleri',$active_module); ?>
<section class="page-intro"><p>Konaklama geçmişi, sadakat puanı, tercihler ve değerlendirme ortalamasıyla misafiri 360° tanıyın; servis taleplerini kayıt altına alıp kapatın.</p></section><?php if($message):?><p class="save-success">✓ <?=htmlspecialchars($message)?></p><?php endif;?><?php if($error):?><p class="login-error"><?=htmlspecialchars($error)?></p><?php endif;?>
<section class="next-module"><h2>Misafir görünümü</h2><?php foreach($guests as $g):?><p><a href="otel-misafir-crm.php?guest=<?=(int)$g['id']?>"><b><?=htmlspecialchars($g['first_name'].' '.$g['last_name'])?></b></a> · <?=htmlspecialchars($g['email']??$g['phone']??'İletişim yok')?> · <?= (int)$g['stays']?> konaklama · son çıkış <?=htmlspecialchars($g['last_stay']??'-')?><?= $g['tier_name']?' · <b>'.htmlspecialchars($g['tier_name']).'</b>':''?><br><small class="muted"><?=number_format((float)$g['points_balance'],0)?> puan · <?=number_format((float)$g['lifetime_nights'],0)?> gece · <?=number_format((float)$g['avg_rating']??0,1)?>★ ort. değerlendirme · pazarlama izni <?= $g['marketing_consent']?'var':'yok'?></small></p><?php endforeach;?></section>
<?php if($detail):?>
<section class="next-module"><h2>Misafir detayı — <?=htmlspecialchars($detail['first_name'].' '.$detail['last_name'])?></h2>
<div class="availability-row"><div><b><?=htmlspecialchars($detail['email']??$detail['phone']??'İletişim yok')?></b><span><?=htmlspecialchars((string)($detail['nationality']??'—'))?> · doğum <?=htmlspecialchars((string)($detail['birth_date']??'—'))?> · VIP: <?=htmlspecialchars((string)($detail['vip_level']??'—'))?></span></div>
<?php if($loyalty??null):?><strong><?=htmlspecialchars((string)($loyalty['tier_name']??'Kademesiz'))?> · <?=number_format((float)$loyalty['points_balance'],0)?> puan</strong><?php endif;?></div>
<?php $prefs=json_decode((string)$detail['preferences'],true)?:[];if($prefs):?><p class="muted">Tercihler: <?=htmlspecialchars(json_encode($prefs,JSON_UNESCAPED_UNICODE))?></p><?php endif;?>
<?php if($loyalty??null):?><p><b>Ömür boyu:</b> <?=number_format((float)$loyalty['lifetime_nights'],0)?> gece · <?=number_format((float)$loyalty['lifetime_revenue'],2)?> gelir<?php if($ledger):?><br><b>Puan hareketleri:</b><br><?php foreach($ledger as $l):?>· <?=htmlspecialchars($l['transaction_type'])?> <?=htmlspecialchars((string)$l['points'])?> — <?=htmlspecialchars((string)$l['description'])?> (<?=htmlspecialchars((string)$l['created_at'])?>)<br><?php endforeach;?><?php endif;?></p>
<?php if($openFolios):?><form method="post" class="supply-form" style="max-width:560px"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="redeem"><input type="hidden" name="guest_id" value="<?=$guestId?>"><div class="form-row"><label>Folyo<select name="folio_id"><?php foreach($openFolios as $f):?><option value="<?=$f['id']?>"><?=htmlspecialchars($f['booking_reference'])?></option><?php endforeach;?></select></label><label>Puan<input type="number" name="points" min="1" max="<?=(int)$loyalty['points_balance']?>" value="<?=(int)$loyalty['points_balance']?>" required></label></div><p class="muted">1 puan = 0,10 EUR folyo kredisi.</p><button>Puanı indirim olarak kullan</button></form><?php else:?><p class="muted">Kullanılabilir açık folyo yok.</p><?php endif;?>
<?php endif;?>
<h3>Konaklama geçmişi</h3><?php if(!$stays):?><p class="muted">Konaklama yok.</p><?php endif;?><?php foreach($stays as $s):?><p><b><?=htmlspecialchars($s['booking_reference'])?></b> · <?=htmlspecialchars($s['property_name'])?> · <?=htmlspecialchars($s['check_in'])?> / <?=htmlspecialchars($s['check_out'])?> · <?=number_format((float)$s['total_amount'],2)?> <?=htmlspecialchars($s['currency'])?> · <?=htmlspecialchars($s['booking_status'])?><?= $s['deposit_amount']>0?' · depozito '.number_format((float)$s['deposit_amount'],2).' ('.htmlspecialchars($s['deposit_status']).')':''?></p><?php endforeach;?>
<h3>Değerlendirmeler</h3><?php if(!$reviews):?><p class="muted">Değerlendirme yok.</p><?php endif;?><?php foreach($reviews as $r):?><p><b><?=htmlspecialchars((string)$r['rating'])?>★</b> <?=htmlspecialchars((string)$r['title'])?> · <?=htmlspecialchars($r['property_name'])?> · <?=htmlspecialchars($r['status'])?><br><?=htmlspecialchars((string)$r['body'])?></p><?php endforeach;?>
</section>
<?php endif;?>
<section class="next-module"><h2>Segment tanımı</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="segment"><div class="form-row"><input name="name" required placeholder="Örn. Aile tatili / yüksek değerli misafir"><input name="criteria" placeholder="Segment kuralı veya açıklaması"></div><button>Segmenti kaydet</button></form><?php foreach($segments as $s): $criteria=json_decode((string)$s['criteria'],true)?:[];?><p><b><?=htmlspecialchars($s['name'])?></b> · <?=htmlspecialchars($criteria['note']??'')?></p><?php endforeach;?></section>
<section class="next-module"><h2>Misafir iletişimi ve hizmet talebi</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="communication"><div class="form-row"><select name="guest_id"><?php foreach($guests as $g):?><option value="<?=$g['id']?>"><?=htmlspecialchars($g['first_name'].' '.$g['last_name'].' · '.$g['email'])?></option><?php endforeach;?></select><select name="channel"><option value="email">E-posta</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="phone">Telefon</option></select><input name="subject" required placeholder="Konu"></div><textarea name="body" required placeholder="İletişim özeti veya gönderilen mesaj"></textarea><button>İletişim kaydı ekle</button></form><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="service_request"><div class="form-row"><select name="guest_id"><?php foreach($guests as $g):?><option value="<?=$g['id']?>"><?=htmlspecialchars($g['first_name'].' '.$g['last_name'])?></option><?php endforeach;?></select><select name="booking_id"><option value="">Rezervasyonsuz</option></select><select name="request_type"><option value="housekeeping">Kat hizmetleri</option><option value="maintenance">Teknik servis</option><option value="restaurant">Restoran</option><option value="transfer">Transfer</option><option value="other">Diğer</option></select><select name="priority"><option value="normal">Normal</option><option value="high">Yüksek</option><option value="urgent">Acil</option></select></div><textarea name="details" required placeholder="Talep detayı"></textarea><button>Talebi aç</button></form></section>
<section class="next-module"><h2>Açık talepler</h2><?php foreach($requests as $r):?><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="request_status"><input type="hidden" name="id" value="<?=$r['id']?>"><b><?=htmlspecialchars($r['first_name'].' '.$r['last_name'])?></b> · <?=htmlspecialchars($r['request_type'])?> · <?=htmlspecialchars($r['details'])?> <select name="status"><option><?=$r['status']?></option><option value="in_progress">in_progress</option><option value="resolved">resolved</option><option value="cancelled">cancelled</option></select><button>Güncelle</button></form><?php endforeach;?></section>
<?php supply_end();
