<?php
declare(strict_types=1);
$active_module='hotel_staff'; require_once __DIR__.'/layout.php';
if(empty($_SESSION['supplier_csrf']))$_SESSION['supplier_csrf']=bin2hex(random_bytes(32));
$u=$supplier_user;$pdo=db();$message='';$error='';
try {if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($_SESSION['supplier_csrf'],(string)($_POST['csrf']??'')))throw new RuntimeException('Güvenlik doğrulaması geçersiz.');$action=$_POST['action']??'';
 if($action==='role'){$code=preg_replace('/[^a-z0-9_]/','_',strtolower(trim((string)$_POST['role_code'])));if(!$code)throw new RuntimeException('Rol kodu zorunludur.');$permissions=array_values(array_filter(array_map('trim',explode(',',(string)$_POST['permissions']))));$pdo->prepare('INSERT INTO hotel_roles(supplier_id,role_code,role_name,permissions) VALUES(?,?,?,?::jsonb) ON CONFLICT(supplier_id,role_code) DO UPDATE SET role_name=EXCLUDED.role_name,permissions=EXCLUDED.permissions')->execute([$u['supplier_id'],$code,trim((string)$_POST['role_name']),json_encode($permissions)]);$message='Rol kaydedildi.';}
 if($action==='staff'){$pin=trim((string)$_POST['pin']);if($pin!==''&&!preg_match('/^\d{4,8}$/',$pin))throw new RuntimeException('PIN 4-8 haneli olmalıdır.');$pdo->prepare('INSERT INTO hotel_staff(supplier_id,full_name,department,role_code,pin_hash,is_active) VALUES(?,?,?,?,?,true)')->execute([$u['supplier_id'],trim((string)$_POST['full_name']),trim((string)$_POST['department']),$_POST['role_code'], $pin!==''?password_hash($pin,PASSWORD_DEFAULT):null]);$message='Personel kaydedildi.';}
 if($action==='toggle'){$pdo->prepare('UPDATE hotel_staff SET is_active=NOT is_active WHERE id=? AND supplier_id=?')->execute([(int)$_POST['id'],$u['supplier_id']]);$message='Personel durumu güncellendi.';}
}}catch(Throwable $e){$error=$e->getMessage();}
$q=$pdo->prepare('SELECT * FROM hotel_roles WHERE supplier_id=? ORDER BY role_name');$q->execute([$u['supplier_id']]);$roles=$q->fetchAll();
$q=$pdo->prepare('SELECT * FROM hotel_staff WHERE supplier_id=? ORDER BY is_active DESC,full_name');$q->execute([$u['supplier_id']]);$staff=$q->fetchAll();
supply_start('Otel personel ve rol yönetimi',$active_module); ?>
<section class="page-intro"><p>Kat hizmetleri, resepsiyon, teknik servis ve gece denetimi ekiplerinin görev kapsamını tanımlayın. PIN yalnızca mobil görev ekranları gibi sonraki kimlik doğrulama adımları için tek yönlü özet olarak saklanır.</p></section><?php if($message):?><p class="save-success">✓ <?=htmlspecialchars($message)?></p><?php endif;?><?php if($error):?><p class="login-error"><?=htmlspecialchars($error)?></p><?php endif;?>
<section class="next-module"><h2>Rol tanımı</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="role"><div class="form-row"><input name="role_code" required placeholder="Örn. housekeeping_supervisor"><input name="role_name" required placeholder="Rol adı"><input name="permissions" placeholder="Yetkiler: housekeeping.read,housekeeping.write"></div><button>Rolü kaydet</button></form><?php foreach($roles as $r):?><p><b><?=htmlspecialchars($r['role_name'])?></b> · <?=htmlspecialchars($r['role_code'])?> · <?=htmlspecialchars((string)$r['permissions'])?></p><?php endforeach;?></section>
<section class="next-module"><h2>Personel ekle</h2><form method="post" class="supply-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="staff"><div class="form-row"><input name="full_name" required placeholder="Ad soyad"><input name="department" required placeholder="Departman"><select name="role_code"><?php foreach($roles as $r):?><option value="<?=htmlspecialchars($r['role_code'])?>"><?=htmlspecialchars($r['role_name'])?></option><?php endforeach;?></select><input name="pin" inputmode="numeric" maxlength="8" placeholder="İsteğe bağlı görev PIN'i"></div><button>Personeli kaydet</button></form></section>
<section class="next-module"><h2>Personel listesi</h2><?php foreach($staff as $s):?><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['supplier_csrf'])?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$s['id']?>"><b><?=htmlspecialchars($s['full_name'])?></b> · <?=htmlspecialchars($s['department'])?> · <?=htmlspecialchars($s['role_code'])?> · <?= $s['is_active']?'aktif':'pasif'?><button><?= $s['is_active']?'Pasifleştir':'Aktifleştir'?></button></form><?php endforeach;?></section>
<?php supply_end();
