<?php
$active_module = 'properties';
require_once __DIR__ . '/layout.php';
require_once __DIR__ . '/../config/hotel_form.php';
require_once __DIR__ . '/../config/listing_integrity.php';
$u = $supplier_user;
$id = filter_input(INPUT_GET, 'product', FILTER_VALIDATE_INT);
if (!$id) { header('Location: /nexustraveltech/tedarikci/tesisler'); exit; }
$q = db()->prepare("SELECT * FROM properties WHERE id=? AND supplier_id=? AND property_type='hotel' LIMIT 1");
$q->execute([$id, $u['supplier_id']]);
$hotel = $q->fetch();
if (!$hotel) { http_response_code(404); exit('Otel bulunamadı.'); }
$details = json_decode($hotel['product_details'] ?? '{}', true) ?: [];
$error = '';
$notice = isset($_GET['published']) ? 'Ürün yayına alındı — acente müsaitlik sorgularında artık görünür.' : (isset($_GET['saved']) ? 'Otel detayları kaydedildi.' : (isset($_GET['room_saved']) ? 'Yeni oda tipi çoğaltıldı; özellik ve fiyatı kaydedildi.' : ''));
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'publish') {
  if (!csrf_valid($_POST['csrf_token'] ?? null)) { $error = 'Güvenlik doğrulaması yenilendi. Lütfen tekrar deneyin.'; }
  else {
    $readiness = listing_readiness($hotel);
    if (!$readiness['ready']) {
      $missing = array_map(fn($i) => $i['label'], array_filter($readiness['items'], fn($i) => !$i['ok']));
      $error = 'Ürün yayına alınamadı — eksik kalemler: ' . implode(', ', $missing) . '.';
    } else {
      db()->prepare("UPDATE properties SET status='active' WHERE id=? AND supplier_id=?")->execute([$id, $u['supplier_id']]);
      record_audit_event('supplier', (int) $u['id'], 'publish', 'property', $id, ['name' => $hotel['name']]);
      header('Location: /nexustraveltech/tedarikci/otel-detay?product=' . $id . '&published=1'); exit;
    }
  }
}
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['room_action'] ?? '') === 'duplicate') {
  if (!csrf_valid($_POST['csrf_token'] ?? null)) { $error = 'Güvenlik doğrulaması yenilendi. Lütfen tekrar deneyin.'; }
  else {
    $sourceId = (int)($_POST['room_source_id'] ?? 0);
    $newName = trim((string)($_POST['room_name'] ?? ''));
    $source = db()->prepare('SELECT r.* FROM room_types r WHERE r.id=? AND r.property_id=? LIMIT 1');
    $source->execute([$sourceId, $id]); $source = $source->fetch();
    if (!$source || $newName === '') { $error = 'Çoğaltılacak oda ve yeni oda adı gereklidir.'; }
    else {
      $roomDetails = json_decode($source['room_details'] ?? '{}', true) ?: [];
      $roomDetails['area_m2'] = max(0, (int)($_POST['room_area'] ?? ($roomDetails['area_m2'] ?? 0)));
      $roomDetails['default_nightly_price'] = max(0, (float)str_replace(',', '.', (string)($_POST['room_price'] ?? ($roomDetails['default_nightly_price'] ?? 0))));
      $roomDetails['price_currency'] = in_array($_POST['room_currency'] ?? 'EUR', ['TRY','EUR','USD','GBP'], true) ? $_POST['room_currency'] : 'EUR';
      $capacity = max(1, min(20, (int)($_POST['room_capacity'] ?? $source['capacity_adults'])));
      $units = max(0, min(9999, (int)($_POST['room_units'] ?? $source['total_units'])));
      db()->prepare('INSERT INTO room_types (property_id,name,capacity_adults,total_units,room_details,status) VALUES (?,?,?,?,?,"active")')->execute([$id,$newName,$capacity,$units,json_encode($roomDetails, JSON_UNESCAPED_UNICODE)]);
      header('Location: /nexustraveltech/tedarikci/otel-detay?product='.$id.'&room_saved=1'); exit;
    }
  }
}
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['room_action'] ?? '') !== 'duplicate') {
  if (!csrf_valid($_POST['csrf_token'] ?? null)) { $error = 'Güvenlik doğrulaması yenilendi. Lütfen tekrar deneyin.'; }
  else {
    $textKeys = ['brand','hotel_class','hotel_type','star_rating','address','district','area','latitude','longitude','airport_distance','beach_distance','short_description','description','check_in','check_out','pet_policy','smoking_policy','minimum_age','board_notes','commission_rate','deposit_rate','collection_model','account_holder','bank_name','iban','payment_note','free_cancellation_until','cancellation_advance_days','cancellation_fee_rate','no_show_fee_rate','refund_method','refund_processing_days','cancellation_note'];
    foreach ($textKeys as $key) { $value=trim((string)($_POST['hotel'][$key] ?? '')); if($value !== '') $details[$key]=$value; else unset($details[$key]); }
    $details['themes'] = array_values(array_intersect($_POST['themes'] ?? [], hotel_themes()));
    $allAmenities = hotel_service_items(hotel_amenity_groups());
    $allActivities = hotel_service_items(hotel_activity_groups());
    $allEvents = hotel_service_items(hotel_event_groups());
    $allServices = array_merge($allAmenities, $allActivities, $allEvents);
    $servicePricing = [];
    foreach (($_POST['service_pricing'] ?? []) as $service => $status) {
      if (in_array($service, $allServices, true) && in_array($status, ['free', 'paid'], true)) $servicePricing[$service] = $status;
    }
    $details['service_pricing'] = $servicePricing;
    $details['amenities'] = array_values(array_intersect(array_keys($servicePricing), $allAmenities));
    $details['activities'] = array_values(array_intersect(array_keys($servicePricing), $allActivities));
    $details['events'] = array_values(array_intersect(array_keys($servicePricing), $allEvents));
    $commission = (float)str_replace(',', '.', $details['commission_rate'] ?? '0');
    $deposit = (float)str_replace(',', '.', $details['deposit_rate'] ?? '0');
    $allowedCollectionModels = ['agency_collects_deposit','agency_collects_full','property_collects_full'];
    // Older listings can be edited section by section; keep a sensible default when
    // their previously optional collection model has not yet been saved.
    $details['collection_model'] = $details['collection_model'] ?? 'agency_collects_deposit';
    if ($commission < 0 || $commission > 100 || $deposit < 0 || $deposit > 100 || !in_array($details['collection_model'], $allowedCollectionModels, true)) {
      $error = 'Komisyon, ön ödeme ve tahsilat modeli bilgilerini kontrol edin.';
    }
    $iban = preg_replace('/\s+/', '', strtoupper($details['iban'] ?? ''));
    if ($iban !== '' && !preg_match('/^TR\d{24}$/', $iban)) $error = 'IBAN, TR ile başlayan 26 karakterlik geçerli bir Türkiye IBAN’ı olmalıdır.';
    $details['iban'] = $iban;
    foreach (['cancellation_advance_days','cancellation_fee_rate','no_show_fee_rate','refund_processing_days'] as $key) {
      $value = (float)str_replace(',', '.', $details[$key] ?? '0');
      $max = $key === 'cancellation_advance_days' ? 365 : ($key === 'refund_processing_days' ? 60 : 100);
      if ($value < 0 || $value > $max) $error = 'İptal ve iade oranlarını kontrol edin.';
    }
    $allowedRefundMethods = ['original_payment','bank_transfer','agency_settlement','voucher'];
    if (($details['refund_method'] ?? '') !== '' && !in_array($details['refund_method'], $allowedRefundMethods, true)) $error = 'Geçerli bir iade yöntemi seçin.';
    if ($error === '') {
    try {
      $pdo = db(); $pdo->beginTransaction();
      $pdo->prepare('UPDATE properties SET product_details=? WHERE id=? AND supplier_id=?')->execute([json_encode($details, JSON_UNESCAPED_UNICODE), $id, $u['supplier_id']]);
      if (!empty($_FILES['media']['name'][0])) {
        $allowed = ['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
        $finfo = new finfo(FILEINFO_MIME_TYPE);
        $dir = dirname(__DIR__) . '/uploads/properties/' . $id;
        if (!is_dir($dir)) mkdir($dir, 0755, true);
        $insert = $pdo->prepare('INSERT INTO property_media (property_id,file_path,file_name,mime_type,is_cover,sort_order) VALUES (?,?,?,?,?,?)');
        foreach ($_FILES['media']['tmp_name'] as $index=>$tmp) {
          if ($_FILES['media']['error'][$index] !== UPLOAD_ERR_OK || $_FILES['media']['size'][$index] > 8*1024*1024) continue;
          $mime = $finfo->file($tmp); if (!isset($allowed[$mime])) continue;
          $filename = bin2hex(random_bytes(12)) . '.' . $allowed[$mime];
          if (move_uploaded_file($tmp, $dir . '/' . $filename)) $insert->execute([$id,'uploads/properties/'.$id.'/'.$filename,basename((string)$_FILES['media']['name'][$index]),$mime,$index===0 ? 1 : 0,$index]);
        }
      }
      $pdo->commit(); header('Location: /nexustraveltech/tedarikci/otel-detay?product='.$id.'&saved=1'); exit;
    } catch (Throwable $e) { if (db()->inTransaction()) db()->rollBack(); $error='Kaydetme sırasında bir sorun oluştu.'; }
    }
  }
}
$media = db()->prepare('SELECT * FROM property_media WHERE property_id=? ORDER BY is_cover DESC, sort_order, id'); $media->execute([$id]); $media=$media->fetchAll();
$rooms = db()->prepare('SELECT * FROM room_types WHERE property_id=? ORDER BY id'); $rooms->execute([$id]); $rooms=$rooms->fetchAll();
$servicePricing = is_array($details['service_pricing'] ?? null) ? $details['service_pricing'] : [];
foreach (['amenities', 'activities', 'events'] as $legacyKey) foreach (($details[$legacyKey] ?? []) as $service) if (!isset($servicePricing[$service])) $servicePricing[$service] = 'free';
supply_start(htmlspecialchars($hotel['name']).' · ilan detayları', $active_module); ?>
<section class="hotel-editor-head"><div><span>OTEL İLAN KURULUMU</span><h2>Satış kanallarına eksiksiz<br>ürün verisi gönderin.</h2><p>İlan tamamlanma durumu: <b><?= count($media) ? 'görseller eklendi' : 'görsel bekliyor' ?></b></p></div><a href="/nexustraveltech/tedarikci/tesisler">← Ürün listesine dön</a></section>
<?php $readiness = listing_readiness($hotel); $linkFor = ['rooms' => '/nexustraveltech/tedarikci/otel-detay?product='.$id.'#sec-04', 'rates' => '/nexustraveltech/tedarikci/fiyat-kontenjan?property='.$id, 'inventory' => '/nexustraveltech/tedarikci/fiyat-kontenjan?property='.$id, 'media' => '/nexustraveltech/tedarikci/otel-detay?product='.$id.'#sec-05', 'description' => '/nexustraveltech/tedarikci/otel-detay?product='.$id.'#sec-02', 'location' => '/nexustraveltech/tedarikci/otel-detay?product='.$id.'#sec-01', 'rules' => '/nexustraveltech/tedarikci/satis-kurallari?property='.$id]; /* Bölümler tek kaynaktan numaralanır — yeni bölüm eklerken yalnızca bu diziye satır ekle. */ $editorSections = ['Kimlik, sınıflandırma & konum' => 'Kimlik & konum', 'Satış içeriği & operasyon' => 'Satış içeriği', 'Olanaklar, aktiviteler & etkinlikler' => 'Olanaklar', 'Oda envanteri & fiyat' => 'Oda envanteri', 'Görseller' => 'Görseller', 'Acente komisyonu & tahsilat' => 'Komisyon & tahsilat', 'İptal & iade şartları' => 'İptal & iade']; $editorToc = []; $editorN = 0; foreach ($editorSections as $fullTitle => $shortTitle) { $editorN++; $editorToc[] = ['id' => 'sec-'.str_pad((string)$editorN, 2, '0', STR_PAD_LEFT), 'no' => str_pad((string)$editorN, 2, '0', STR_PAD_LEFT), 'title' => $fullTitle, 'short' => $shortTitle]; } $editorN = 0; ?>
<section class="publish-panel"><div class="publish-head"><div><span>YAYINA ALMA AKIŞI</span><h3>Hazırlık kontrol listesi · <b><?= $readiness['score'] ?>/100</b></h3><p>Altı çekirdek kalem tamamlandığında ürün tek tıkla yayına alınır; satış kuralı opsiyoneldir.</p></div><?php if ($hotel['status'] === 'active'): ?><b class="status active-status">YAYINDA</b><?php else: ?><form method="post" class="publish-form"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="action" value="publish"><?php if ($readiness['ready']): ?><button class="primary-button" onclick="return confirm('Ürün yayına alınsın mı? Acente müsaitlik sorgularında görünür olur.');">Yayına al →</button><?php else: ?><span class="ghost-button disabled" title="Eksik kalemler tamamlanmadan yayına alınamaz.">Yayına al</span><?php endif; ?></form><?php endif; ?></div><ul class="readiness-check"><?php foreach ($readiness['items'] as $item): ?><li class="<?= $item['ok'] ? 'ok' : 'missing' ?>"><?= $item['ok'] ? '✓' : '✗' ?> <?= htmlspecialchars($item['label']) ?><small><?= htmlspecialchars($item['detail']) ?></small><?php if (!$item['ok']): ?><a href="<?= htmlspecialchars($linkFor[$item['key']] ?? '#') ?>">Doldur →</a><?php else: ?><a class="readiness-all-view" href="<?= htmlspecialchars($linkFor[$item['key']] ?? '#') ?>">Gör →</a> <button type="button" class="ical-copy-btn" data-copy="<?= htmlspecialchars($linkFor[$item['key']] ?? '#') ?>" title="URL'yi kopyala">⧉ Kopyala</button><?php endif; ?></li><?php endforeach; ?></ul></section>
<?php if($error): ?><p class="login-error"><?= htmlspecialchars($error) ?></p><?php endif; ?><?php if($notice): ?><p class="save-success">✓ <?= htmlspecialchars($notice) ?></p><?php endif; ?>
<?php $webhookSt = db()->prepare("SELECT display_name, channel_code, access_token, status FROM channel_connections WHERE supplier_id=? AND access_token IS NOT NULL AND access_token<>'' ORDER BY status='active' DESC, display_name"); $webhookSt->execute([$u['supplier_id']]); $webhooks = $webhookSt->fetchAll(); if ($webhooks): ?><section class="publish-panel" style="margin-top:18px"><div class="publish-head"><div><span>ENTEGRASYON</span><h3>Kanal webhook adresleri</h3><p>Kanal tarafına bildirimler için verdiğiniz webhook adresleri. Bağlantı pasifleşirse kanal bu adrese bildirim gönderemez.</p></div><a href="/nexustraveltech/tedarikci/dagitim-merkezi">Dağıtım & kanal merkezi →</a></div><?php foreach ($webhooks as $wh): $whFull = 'https://nexustraveltech.com/api/channel-webhook?token=' . $wh['access_token']; $whShort = 'api/channel-webhook?token=' . mb_substr((string) $wh['access_token'], 0, 10) . '…' . mb_substr((string) $wh['access_token'], 30, 4) . '…'; ?><div class="ical-url-box" style="max-width:680px;margin:8px 0"><span class="ical-url-label" title="<?= htmlspecialchars($whFull) ?>"><?= htmlspecialchars($wh['display_name']) ?> · <?= htmlspecialchars($whShort) ?><?= $wh['status'] === 'active' ? '' : ' · ' . htmlspecialchars($wh['status']) ?></span><button type="button" class="ical-copy-btn" data-copy="<?= htmlspecialchars($whFull) ?>">Kopyala</button></div><?php endforeach; ?></section><?php endif; ?>
<div class="hotel-editor-wrap"><aside class="editor-toc"><div class="editor-toc-head"><span>İÇİNDEKİLER</span><b>7 bölüm</b></div><nav><?php foreach ($editorToc as $t): ?><a href="#<?= $t['id'] ?>"><span><?= $t['no'] ?></span><?= htmlspecialchars($t['short']) ?></a><?php endforeach; ?></nav><p class="editor-toc-hint">Bölüme gitmek için tıklayın.</p></aside><form method="post" enctype="multipart/form-data" class="hotel-editor"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrf_token()) ?>">
<?php $sec = $editorToc[$editorN++]; ?><section id="<?= $sec['id'] ?>" class="editor-section"><div class="editor-title"><span><?= $sec['no'] ?></span><div><h3><?= htmlspecialchars($sec['title']) ?></h3><p>Tesis tipi, yıldız seviyesi ve konum bilgileri acente filtrelerini besler.</p></div></div><div class="editor-fields"><label>Marka / zincir<input name="hotel[brand]" value="<?= htmlspecialchars($details['brand'] ?? '') ?>" placeholder="Örn. NEXUS Hotels"></label><label>Tesis tipi<select name="hotel[hotel_type]"><option value="">Seçin</option><?php foreach(hotel_property_types() as $item): ?><option value="<?= htmlspecialchars($item) ?>" <?= ($details['hotel_type']??'')===$item?'selected':'' ?>><?= htmlspecialchars($item) ?></option><?php endforeach; ?></select></label><label>Yıldız seviyesi<select name="hotel[star_rating]"><option value="">Seçin</option><?php foreach(hotel_star_ratings() as $item): ?><option value="<?= htmlspecialchars($item) ?>" <?= ($details['star_rating']??'')===$item?'selected':'' ?>><?= htmlspecialchars($item) ?></option><?php endforeach; ?></select></label><label>Ek sınıf notu<input name="hotel[hotel_class]" value="<?= htmlspecialchars($details['hotel_class'] ?? '') ?>" placeholder="Örn. lüks, premium"></label><label class="wide">Açık adres<input name="hotel[address]" value="<?= htmlspecialchars($details['address'] ?? '') ?>" placeholder="Mahalle, cadde, kapı no"></label><label>İlçe<input name="hotel[district]" value="<?= htmlspecialchars($details['district'] ?? '') ?>" placeholder="Örn. Kundu"></label><label>Mevkii / bölge<input name="hotel[area]" value="<?= htmlspecialchars($details['area'] ?? '') ?>" placeholder="Örn. Lara"></label><label>Havalimanı mesafesi<input name="hotel[airport_distance]" value="<?= htmlspecialchars($details['airport_distance'] ?? '') ?>" placeholder="Örn. 15 km"></label><label>Plaj mesafesi<input name="hotel[beach_distance]" value="<?= htmlspecialchars($details['beach_distance'] ?? '') ?>" placeholder="Örn. Denize sıfır"></label><label>Enlem<input name="hotel[latitude]" value="<?= htmlspecialchars($details['latitude'] ?? '') ?>" placeholder="36.8..."></label><label>Boylam<input name="hotel[longitude]" value="<?= htmlspecialchars($details['longitude'] ?? '') ?>" placeholder="30.6..."></label></div></section>
<?php $sec = $editorToc[$editorN++]; ?><section id="<?= $sec['id'] ?>" class="editor-section"><div class="editor-title"><span><?= $sec['no'] ?></span><div><h3><?= htmlspecialchars($sec['title']) ?></h3><p>İlan metni, giriş-çıkış ve tesis kuralları.</p></div></div><div class="editor-fields"><label class="wide">Kısa açıklama<textarea name="hotel[short_description]" maxlength="300" placeholder="Tesis kartında görünecek kısa satış cümlesi."><?= htmlspecialchars($details['short_description'] ?? '') ?></textarea></label><label class="wide">Detaylı açıklama<textarea name="hotel[description]" rows="6" placeholder="Tesisin deneyimi, konumu ve öne çıkan yönleri."><?= htmlspecialchars($details['description'] ?? '') ?></textarea></label><label>Giriş saati<input type="time" name="hotel[check_in]" value="<?= htmlspecialchars($details['check_in'] ?? '14:00') ?>"></label><label>Çıkış saati<input type="time" name="hotel[check_out]" value="<?= htmlspecialchars($details['check_out'] ?? '12:00') ?>"></label><label>Evcil hayvan<select name="hotel[pet_policy]"><option><?= htmlspecialchars($details['pet_policy'] ?? 'Kabul edilmez') ?></option><option>Kabul edilir</option><option>Talep üzerine</option><option>Kabul edilmez</option></select></label><label>Sigara politikası<select name="hotel[smoking_policy]"><option><?= htmlspecialchars($details['smoking_policy'] ?? 'Sigara içilmez') ?></option><option>Sigara içilmez</option><option>Belirlenmiş alanlarda</option><option>Odada içilebilir</option></select></label><label>Minimum konaklama yaşı<input type="number" name="hotel[minimum_age]" value="<?= htmlspecialchars($details['minimum_age'] ?? '') ?>" min="0" placeholder="Örn. 16"></label><label class="wide">Konsept / servis notları<textarea name="hotel[board_notes]" placeholder="Öğün saatleri, a la carte restoran, ücretli/ücretsiz servis ayrıntıları."><?= htmlspecialchars($details['board_notes'] ?? '') ?></textarea></label></div></section>
<?php $sec = $editorToc[$editorN++]; ?><section id="<?= $sec['id'] ?>" class="editor-section"><div class="editor-title"><span><?= $sec['no'] ?></span><div><h3><?= htmlspecialchars($sec['title']) ?></h3><p>Sunulan her hizmet için durumunu belirtin. Ücretli seçenekler acente ve misafire ayrı şekilde gösterilir.</p></div></div><div class="editor-options"><h4>Temalar</h4><div class="check-grid"><?php foreach(hotel_themes() as $item): ?><label><input type="checkbox" name="themes[]" value="<?= htmlspecialchars($item) ?>" <?= in_array($item,$details['themes'] ?? [],true)?'checked':'' ?>><?= htmlspecialchars($item) ?></label><?php endforeach; ?></div><?php foreach (['Tesis olanakları' => hotel_amenity_groups(), 'Aktiviteler' => hotel_activity_groups(), 'Etkinlikler' => hotel_event_groups()] as $sectionTitle => $groups): ?><h4 class="service-section-title"><?= htmlspecialchars($sectionTitle) ?></h4><?php foreach($groups as $group=>$items): ?><p class="service-group-name"><?= htmlspecialchars($group) ?></p><div class="service-grid"><?php foreach($items as $item): $status=$servicePricing[$item] ?? ''; ?><label><span><?= htmlspecialchars($item) ?></span><select name="service_pricing[<?= htmlspecialchars($item) ?>]"><option value="" <?= $status===''?'selected':'' ?>>Sunulmuyor</option><option value="free" <?= $status==='free'?'selected':'' ?>>Ücretsiz</option><option value="paid" <?= $status==='paid'?'selected':'' ?>>Ücretli</option></select></label><?php endforeach; ?></div><?php endforeach; ?><?php endforeach; ?></div></section>
<?php $sec = $editorToc[$editorN++]; ?><section id="<?= $sec['id'] ?>" class="editor-section"><div class="editor-title"><span><?= $sec['no'] ?></span><div><h3><?= htmlspecialchars($sec['title']) ?></h3><p>Mevcut bir oda tipini temel alarak çoğaltın; yalnızca değişen kapasite, m², adet ve başlangıç fiyatını düzenleyin.</p></div></div><div class="editor-fields"><div class="wide room-summary"><?php if($rooms): ?><?php foreach($rooms as $room): $roomInfo=json_decode($room['room_details']??'{}',true)?:[]; ?><article><b><?= htmlspecialchars($room['name']) ?></b><span><?= (int)$room['capacity_adults'] ?> yetişkin · <?= (int)$room['total_units'] ?> adet · <?= (int)($roomInfo['area_m2']??0) ?> m²</span><em><?= htmlspecialchars((string)($roomInfo['default_nightly_price']??'—')) ?> <?= htmlspecialchars((string)($roomInfo['price_currency']??'EUR')) ?> / gece</em></article><?php endforeach; ?><?php else: ?><p>Henüz oda tipi yok. İlk oda tipini tesis kurulumundan ekleyin.</p><?php endif; ?></div><label class="wide">Çoğaltılacak oda tipi<select name="room_source_id"><?php foreach($rooms as $room): ?><option value="<?= (int)$room['id'] ?>"><?= htmlspecialchars($room['name']) ?></option><?php endforeach; ?></select></label><label>Yeni oda / villa adı<input name="room_name" placeholder="Örn. Deluxe deniz manzaralı oda"></label><label>Yetişkin kapasitesi<input type="number" name="room_capacity" min="1" max="20" value="2"></label><label>Toplam adet<input type="number" name="room_units" min="0" value="0"></label><label>Alan (m²)<input type="number" name="room_area" min="0" placeholder="Örn. 32"></label><label>Başlangıç gece fiyatı<input type="number" name="room_price" min="0" step="0.01" placeholder="Örn. 180"></label><label>Para birimi<select name="room_currency"><option>EUR</option><option>TRY</option><option>USD</option><option>GBP</option></select></label><div class="wide"><button class="room-copy-button" type="submit" name="room_action" value="duplicate" <?= $rooms ? '' : 'disabled' ?>>Seçili odayı çoğalt ve kaydet →</button></div></div></section>
<?php $sec = $editorToc[$editorN++]; ?><section id="<?= $sec['id'] ?>" class="editor-section"><div class="editor-title"><span><?= $sec['no'] ?></span><div><h3><?= htmlspecialchars($sec['title']) ?></h3><p>JPG, PNG veya WEBP; her dosya en fazla 8 MB. İlk görsel kapak olarak kullanılır.</p></div></div><div class="editor-media"><input type="file" name="media[]" accept="image/jpeg,image/png,image/webp" multiple><div class="media-list"><?php foreach($media as $image): ?><img src="/nexustraveltech/<?= htmlspecialchars($image['file_path']) ?>" alt="<?= htmlspecialchars($hotel['name']) ?> görseli"><?php endforeach; ?></div></div></section>
<?php $sec = $editorToc[$editorN++]; ?><section id="<?= $sec['id'] ?>" class="editor-section"><div class="editor-title"><span><?= $sec['no'] ?></span><div><h3><?= htmlspecialchars($sec['title']) ?></h3><p>Bu kurallar yalnızca yetkili acentelere gösterilir. Komisyon ve tahsilat modeli her fiyat planı için daha sonra ayrı ayrı özelleştirilebilir.</p></div></div><div class="editor-fields"><label>Acente komisyonu (%)<input type="number" name="hotel[commission_rate]" min="0" max="100" step="0.01" value="<?= htmlspecialchars($details['commission_rate'] ?? '') ?>" placeholder="Örn. 15"></label><label>İlk rezervasyonda ön ödeme (%)<input type="number" name="hotel[deposit_rate]" min="0" max="100" step="0.01" value="<?= htmlspecialchars($details['deposit_rate'] ?? '') ?>" placeholder="Örn. 30"></label><label class="wide">Tahsilat modeli<select name="hotel[collection_model]" id="collection-model"><option value="agency_collects_deposit" <?= ($details['collection_model'] ?? '')==='agency_collects_deposit'?'selected':'' ?>>Acente yalnızca ön ödemeyi alır, kalan tutar tesiste ödenir</option><option value="agency_collects_full" <?= ($details['collection_model'] ?? '')==='agency_collects_full'?'selected':'' ?>>Acente tüm ödemeyi alır ve tedarikçiye aktarır</option><option value="property_collects_full" <?= ($details['collection_model'] ?? '')==='property_collects_full'?'selected':'' ?>>Tüm ödeme doğrudan tesiste / tedarikçide alınır</option></select></label><div class="payment-account wide" id="payment-account"><p class="field-heading">Tedarikçi ödeme hesabı</p><p class="account-note">Acente tüm ödemeyi aldığında veya ön ödemeyi tedarikçiye aktarması gerektiğinde, ödeme bu hesaba yönlendirilir.</p><div class="account-grid"><label>Hesap sahibi / ünvan<input name="hotel[account_holder]" value="<?= htmlspecialchars($details['account_holder'] ?? '') ?>" placeholder="Şirket ünvanı veya hesap sahibi"></label><label>Banka adı<input name="hotel[bank_name]" value="<?= htmlspecialchars($details['bank_name'] ?? '') ?>" placeholder="Örn. X Bankası"></label><label class="wide">IBAN<input name="hotel[iban]" value="<?= htmlspecialchars($details['iban'] ?? '') ?>" maxlength="34" placeholder="TR00 0000 0000 0000 0000 0000 00" autocomplete="off"></label><label class="wide">Acente için ödeme notu<textarea name="hotel[payment_note]" placeholder="Örn. Rezervasyon numarası açıklamaya yazılmalıdır. Ödeme vadesi ve mutabakat notları."><?= htmlspecialchars($details['payment_note'] ?? '') ?></textarea></label></div></div></div></section>
<?php $sec = $editorToc[$editorN++]; ?><section id="<?= $sec['id'] ?>" class="editor-section"><div class="editor-title"><span><?= $sec['no'] ?></span><div><h3><?= htmlspecialchars($sec['title']) ?></h3><p>Bu koşullar fiyat planı bazında farklılaştırılabilir. Buradaki kurallar tesisin varsayılan satış koşullarıdır.</p></div></div><div class="editor-fields"><label>Ücretsiz iptal son tarihi<select name="hotel[free_cancellation_until]"><option value="arrival_day" <?= ($details['free_cancellation_until']??'')==='arrival_day'?'selected':'' ?>>Giriş günü</option><option value="before_arrival" <?= ($details['free_cancellation_until']??'')==='before_arrival'?'selected':'' ?>>Girişten belirli gün önce</option><option value="non_refundable" <?= ($details['free_cancellation_until']??'')==='non_refundable'?'selected':'' ?>>Ücretsiz iptal yok / iade edilemez</option></select></label><label>Ücretsiz iptal için süre (gün)<input type="number" name="hotel[cancellation_advance_days]" min="0" max="365" value="<?= htmlspecialchars($details['cancellation_advance_days'] ?? '') ?>" placeholder="Örn. 7"></label><label>Geç iptal kesintisi (%)<input type="number" name="hotel[cancellation_fee_rate]" min="0" max="100" step="0.01" value="<?= htmlspecialchars($details['cancellation_fee_rate'] ?? '') ?>" placeholder="Örn. 50"></label><label>No-show kesintisi (%)<input type="number" name="hotel[no_show_fee_rate]" min="0" max="100" step="0.01" value="<?= htmlspecialchars($details['no_show_fee_rate'] ?? '') ?>" placeholder="Örn. 100"></label><label>İade yöntemi<select name="hotel[refund_method]"><option value="" <?= empty($details['refund_method'])?'selected':'' ?>>İade yöntemi seçin</option><option value="original_payment" <?= ($details['refund_method']??'')==='original_payment'?'selected':'' ?>>Ödemenin yapıldığı karta/kanala iade</option><option value="bank_transfer" <?= ($details['refund_method']??'')==='bank_transfer'?'selected':'' ?>>Banka havalesi</option><option value="agency_settlement" <?= ($details['refund_method']??'')==='agency_settlement'?'selected':'' ?>>Acente cari mutabakatı</option><option value="voucher" <?= ($details['refund_method']??'')==='voucher'?'selected':'' ?>>Kupon / açık tarih hakkı</option></select></label><label>İade işlem süresi (iş günü)<input type="number" name="hotel[refund_processing_days]" min="0" max="60" value="<?= htmlspecialchars($details['refund_processing_days'] ?? '') ?>" placeholder="Örn. 7"></label><label class="wide">Özel iptal & iade notu<textarea name="hotel[cancellation_note]" rows="4" placeholder="Erken rezervasyon, kampanya, resmi tatil, grup rezervasyonu veya tarih değişikliği için özel şartlar."><?= htmlspecialchars($details['cancellation_note'] ?? '') ?></textarea></label></div></section>
<div class="editor-save"><a href="/nexustraveltech/tedarikci/tesisler">Daha sonra tamamla</a><button type="submit">Tüm detayları kaydet →</button></div></form><script>document.querySelectorAll('.editor-toc nav a').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();var id=this.getAttribute('href').slice(1),el=document.getElementById(id);if(el){var y=el.getBoundingClientRect().top+window.scrollY-110;window.scrollTo({top:y,behavior:'smooth'})}})});var tocLinks=document.querySelectorAll('.editor-toc nav a'),sections=document.querySelectorAll('.editor-section');function markToc(){var pos=window.scrollY+140,current='';sections.forEach(function(s){if(s.offsetTop<=pos)current=s.id});tocLinks.forEach(function(a){a.classList.toggle('active',a.getAttribute('href')==='#'+current)})}window.addEventListener('scroll',markToc,{passive:true});markToc();if(location.hash){var hEl=document.querySelector(location.hash);if(hEl){setTimeout(function(){var hy=hEl.getBoundingClientRect().top+window.scrollY-110;window.scrollTo({top:hy,behavior:'smooth'})},80)}}function fallbackCopy(text){var ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy')}catch(e){}document.body.removeChild(ta)}document.querySelectorAll('.ical-copy-btn').forEach(function(b){b.addEventListener('click',function(){var url=this.getAttribute('data-copy'),btn=this;function done(){btn.textContent='Kopyalandı ✓';btn.classList.add('copied');setTimeout(function(){btn.textContent='Kopyala';btn.classList.remove('copied')},1600)}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(url).then(done).catch(function(){fallbackCopy(url);done()})}else{fallbackCopy(url);done()}})});</script></div><?php supply_end(); ?>
