<?php $active_page = 'company'; $seo_page = 'company'; ?>
<!doctype html>
<html lang="tr"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Hakkımızda | NEXUS TravelTech</title><?php require __DIR__ . '/partials/seo.php'; ?><link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&family=Playfair+Display:ital,wght@0,600;0,700;1,600&display=swap" rel="stylesheet" /><link rel="stylesheet" href="/nexustraveltech/assets/styles.css" /></head>
<body class="inner-page"><main><?php require __DIR__ . '/partials/header.php'; ?>
<section class="inner-hero shell"><div class="eyebrow"><i></i> NEXUS TRAVELTECH</div><h1>Sahadaki deneyimi,<br /><em>geleceğin altyapısına</em> taşıyoruz.</h1><p>Otuz yıllık turizm birikiminden doğan NEXUS; operasyonun gerçek ihtiyaçlarını anlayan, teknolojiyi bu ihtiyaçlara göre tasarlayan yeni nesil bir TravelTech şirketidir.</p></section>
<section class="manifesto"><div class="shell"><p class="mono">HAKKIMIZDA</p><h2>Turizmi ekrandan değil, <em>sahanın içinden</em> tanıyoruz.</h2><p>Otuz yıla yayılan birikimimiz; otel rezervasyonundan villa ve yat kiralamaya, araç kiralamadan restoran işletmeciliğine kadar turizmin farklı katmanlarında oluştu. Bu deneyim bize aynı gerçeği tekrar tekrar gösterdi: Turizmde hız, doğru bilginin doğru zamanda doğru kişiye ulaşmasıyla başlar.<br /><br />NEXUS TravelTech’i bu nedenle kuruyoruz. Amacımız, yıllar içinde sahada edinilmiş operasyon bilgisi ve ticari refleksleri yazılıma aktarmak; tedarikçilerin, acentelerin ve satış kanallarının daha hızlı, daha şeffaf ve daha profesyonel çalışabileceği ortak bir altyapı oluşturmaktır.</p></div></section>
<section class="vision-mission"><div class="shell"><article><p class="mono">VİZYONUMUZ</p><h2>Turizmin en güvenilir <em>bağlantı altyapısı</em> olmak.</h2><p>Farklı ürünleri, işletmeleri ve satış kanallarını yaşayan bir bilgi ağı üzerinde bir araya getirerek; turizm sektörünün karar alma ve satış hızını küresel ölçekte ileri taşımayı hedefliyoruz.</p></article><article><p class="mono">MİSYONUMUZ</p><h2>Deneyimi teknolojiye, <em>teknolojiyi sonuca</em> dönüştürmek.</h2><p>Turizm profesyonellerinin günlük iş yükünü azaltan; ürün, fiyat ve müsaitlik bilgisini doğru kaynaktan anında ulaştıran; kolay kullanılan, erişilebilir ve güçlü yazılımlar geliştirmek için çalışıyoruz.</p></article></div></section>
<section class="principles shell"><div class="section-intro"><div class="eyebrow"><i></i> YAKLAŞIMIMIZ</div><h2>Deneyimle güçlenen<br /><em>temel ilkeler.</em></h2></div><div class="principle-list"><article><span>01</span><div><h3>Sahadan gelen tasarım</h3><p>Her özelliği gerçek operasyon akışlarını, satış baskısını ve misafir beklentisini anlayarak tasarlarız.</p></div></article><article><span>02</span><div><h3>Doğru kaynak, anlık bilgi</h3><p>Bilginin sahibi olan tedarikçiyi merkeze alır; aradaki gecikmeyi ve belirsizliği azaltırız.</p></div></article><article><span>03</span><div><h3>Profesyonel ama erişilebilir</h3><p>Güçlü teknolojiyi yalnızca büyük oyuncular için değil, sektörde büyümek isteyen her işletme için ulaşılabilir kılmayı amaçlarız.</p></div></article></div></section>
<section class="inner-cta"><div class="shell"><p>NEXUS İLE BAĞLANIN</p><h2>Turizmin yeni<br />altyapısını birlikte kuralım.</h2><a class="button button-dark" href="/nexustraveltech/#erken-erisim">Pilot programa başvur →</a></div></section>
</main><?php require __DIR__ . '/partials/footer.php'; ?></body></html>
