CREATE TABLE IF NOT EXISTS supplier_discounts (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,rate_plan_id BIGINT REFERENCES rate_plans(id) ON DELETE SET NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,discount_type VARCHAR(12) NOT NULL CHECK(discount_type IN ('percent','fixed')),discount_value NUMERIC(12,2) NOT NULL CHECK(discount_value>0),currency CHAR(3),status VARCHAR(16) NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(end_date>=start_date));
CREATE TABLE IF NOT EXISTS agency_discount_requests (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,agency_id BIGINT NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,rate_plan_id BIGINT REFERENCES rate_plans(id) ON DELETE SET NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,requested_discount_percent NUMERIC(5,2),requested_price NUMERIC(12,2),currency CHAR(3),message TEXT,status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','expired')),approved_discount_percent NUMERIC(5,2),approved_price NUMERIC(12,2),approved_by BIGINT REFERENCES supplier_users(id),approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agency_special_rates (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,agency_id BIGINT NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,rate_plan_id BIGINT REFERENCES rate_plans(id) ON DELETE SET NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,discount_percent NUMERIC(5,2),fixed_price NUMERIC(12,2),currency CHAR(3),request_id BIGINT REFERENCES agency_discount_requests(id) ON DELETE SET NULL,status VARCHAR(16) NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sms_packages (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,code VARCHAR(40) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,credit_count INTEGER NOT NULL CHECK(credit_count>0),price_amount NUMERIC(12,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'TRY',is_active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sms_entitlements (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,account_type VARCHAR(16) NOT NULL CHECK(account_type IN ('supplier','agency')),account_id BIGINT NOT NULL,is_enabled BOOLEAN NOT NULL DEFAULT false,credits_remaining INTEGER NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(account_type,account_id));
CREATE TABLE IF NOT EXISTS sms_outbox (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,account_type VARCHAR(16) NOT NULL,account_id BIGINT NOT NULL,phone VARCHAR(40) NOT NULL,message TEXT NOT NULL,related_type VARCHAR(40),related_id BIGINT,status VARCHAR(16) NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','sent','failed','skipped')),provider_message_id VARCHAR(120),error_message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),sent_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_sms_outbox_status ON sms_outbox(status,created_at);

-- ============================================================
-- Sahiplikten bağımsız çalışma (GRANT + ALTER OWNER):
-- Migration ister postgres ister app kullanıcısıyla koşsun, dokunulan tablolar
-- app DB kullanıcısına devredilir. @APP_DB_USER@ yer tutucusu çalıştırıcı
-- tarafından secrets.php deki db_user ile değiştirilir (config/health.php ve
-- scripts/apply-migrations-postgres.sh); elle psql -f ile koşarsanız önce
-- sed "s/@APP_DB_USER@/<kullanici>/g" ile değiştirin.
GRANT ALL PRIVILEGES ON TABLE supplier_discounts, agency_discount_requests, agency_special_rates, sms_packages, sms_entitlements, sms_outbox TO @APP_DB_USER@;
ALTER TABLE supplier_discounts OWNER TO @APP_DB_USER@;
ALTER TABLE agency_discount_requests OWNER TO @APP_DB_USER@;
ALTER TABLE agency_special_rates OWNER TO @APP_DB_USER@;
ALTER TABLE sms_packages OWNER TO @APP_DB_USER@;
ALTER TABLE sms_entitlements OWNER TO @APP_DB_USER@;
ALTER TABLE sms_outbox OWNER TO @APP_DB_USER@;
