-- Hotel PMS operational core: physical rooms, guests, folios, housekeeping and service operations.
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS source_code VARCHAR(60) NOT NULL DEFAULT 'manual';
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS channel_connection_id BIGINT REFERENCES channel_connections(id) ON DELETE SET NULL;
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS booking_status VARCHAR(24) NOT NULL DEFAULT 'reserved';
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS option_expires_at TIMESTAMPTZ;
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS checked_in_at TIMESTAMPTZ;
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS checked_out_at TIMESTAMPTZ;
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE TABLE IF NOT EXISTS physical_rooms (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,room_type_id BIGINT REFERENCES room_types(id) ON DELETE SET NULL,room_number VARCHAR(40) NOT NULL,floor_label VARCHAR(40),status VARCHAR(20) NOT NULL DEFAULT 'clean' CHECK(status IN ('clean','dirty','inspected','out_of_order','out_of_service','occupied')),notes TEXT,UNIQUE(property_id,room_number));
CREATE TABLE IF NOT EXISTS guest_profiles (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,first_name VARCHAR(100) NOT NULL,last_name VARCHAR(100) NOT NULL,email VARCHAR(190),phone VARCHAR(40),nationality CHAR(2),birth_date DATE,identity_type VARCHAR(30),identity_number VARCHAR(120),passport_country CHAR(2),vip_level VARCHAR(30),marketing_consent BOOLEAN NOT NULL DEFAULT false,preferences JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(supplier_id,email));
CREATE TABLE IF NOT EXISTS booking_guests (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,booking_id BIGINT NOT NULL REFERENCES supplier_bookings(id) ON DELETE CASCADE,guest_id BIGINT NOT NULL REFERENCES guest_profiles(id) ON DELETE CASCADE,is_primary BOOLEAN NOT NULL DEFAULT false,checkin_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK(checkin_status IN ('pending','submitted','verified','checked_in')),UNIQUE(booking_id,guest_id));
CREATE TABLE IF NOT EXISTS booking_rooms (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,booking_id BIGINT NOT NULL REFERENCES supplier_bookings(id) ON DELETE CASCADE,room_type_id BIGINT REFERENCES room_types(id) ON DELETE SET NULL,physical_room_id BIGINT REFERENCES physical_rooms(id) ON DELETE SET NULL,adults SMALLINT NOT NULL DEFAULT 2,children SMALLINT NOT NULL DEFAULT 0,nightly_rate NUMERIC(12,2) NOT NULL DEFAULT 0,currency CHAR(3) NOT NULL DEFAULT 'EUR',status VARCHAR(20) NOT NULL DEFAULT 'reserved' CHECK(status IN ('reserved','checked_in','checked_out','cancelled','no_show')),UNIQUE(booking_id,physical_room_id));
CREATE TABLE IF NOT EXISTS booking_folios (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,booking_id BIGINT NOT NULL REFERENCES supplier_bookings(id) ON DELETE CASCADE,folio_type VARCHAR(20) NOT NULL DEFAULT 'guest' CHECK(folio_type IN ('guest','agency','company')),currency CHAR(3) NOT NULL DEFAULT 'EUR',status VARCHAR(16) NOT NULL DEFAULT 'open' CHECK(status IN ('open','locked','closed')),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS folio_transactions (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,folio_id BIGINT NOT NULL REFERENCES booking_folios(id) ON DELETE CASCADE,transaction_type VARCHAR(20) NOT NULL CHECK(transaction_type IN ('room_charge','service_charge','payment','refund','adjustment','tax')),department VARCHAR(100),description VARCHAR(255) NOT NULL,amount NUMERIC(12,2) NOT NULL,transaction_at TIMESTAMPTZ NOT NULL DEFAULT now(),created_by BIGINT REFERENCES supplier_users(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS idx_folio_transactions_folio ON folio_transactions(folio_id,transaction_at);
CREATE TABLE IF NOT EXISTS housekeeping_tasks (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,physical_room_id BIGINT REFERENCES physical_rooms(id) ON DELETE SET NULL,task_type VARCHAR(30) NOT NULL DEFAULT 'cleaning',priority VARCHAR(12) NOT NULL DEFAULT 'normal',status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK(status IN ('open','assigned','in_progress','inspected','completed')),assigned_to VARCHAR(190),due_at TIMESTAMPTZ,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS maintenance_tickets (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,physical_room_id BIGINT REFERENCES physical_rooms(id) ON DELETE SET NULL,title VARCHAR(190) NOT NULL,description TEXT,priority VARCHAR(12) NOT NULL DEFAULT 'normal',status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK(status IN ('open','assigned','in_progress','resolved','cancelled')),assigned_to VARCHAR(190),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),resolved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS property_services (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,service_type VARCHAR(40) NOT NULL,name VARCHAR(190) NOT NULL,duration_minutes SMALLINT,capacity INTEGER,price NUMERIC(12,2) NOT NULL DEFAULT 0,currency CHAR(3) NOT NULL DEFAULT 'EUR',is_active BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS service_bookings (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_service_id BIGINT NOT NULL REFERENCES property_services(id) ON DELETE CASCADE,booking_id BIGINT REFERENCES supplier_bookings(id) ON DELETE SET NULL,guest_id BIGINT REFERENCES guest_profiles(id) ON DELETE SET NULL,starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ,quantity INTEGER NOT NULL DEFAULT 1,status VARCHAR(20) NOT NULL DEFAULT 'reserved',folio_id BIGINT REFERENCES booking_folios(id) ON DELETE SET NULL,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS hotel_daily_closures (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,business_date DATE NOT NULL,closed_by BIGINT REFERENCES supplier_users(id) ON DELETE SET NULL,closed_at TIMESTAMPTZ NOT NULL DEFAULT now(),notes TEXT,UNIQUE(property_id,business_date));
