-- Commercial PMS core: groups, room movements, multi-folio, payment allocation, invoice and night-audit controls.
CREATE TABLE IF NOT EXISTS booking_groups (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,group_code VARCHAR(60) NOT NULL,group_name VARCHAR(190) NOT NULL,agency_id BIGINT REFERENCES agencies(id) ON DELETE SET NULL,status VARCHAR(20) NOT NULL DEFAULT 'option' CHECK(status IN ('option','confirmed','cancelled','lost')),option_expires_at TIMESTAMPTZ,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(supplier_id,group_code));
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS group_id BIGINT REFERENCES booking_groups(id) ON DELETE SET NULL;
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS confirmation_number VARCHAR(100);
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;
ALTER TABLE supplier_bookings ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS booking_room_moves (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,booking_room_id BIGINT NOT NULL REFERENCES booking_rooms(id) ON DELETE CASCADE,from_physical_room_id BIGINT REFERENCES physical_rooms(id) ON DELETE SET NULL,to_physical_room_id BIGINT REFERENCES physical_rooms(id) ON DELETE SET NULL,effective_at TIMESTAMPTZ NOT NULL DEFAULT now(),reason VARCHAR(255),moved_by BIGINT REFERENCES supplier_users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS booking_options (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,booking_id BIGINT NOT NULL REFERENCES supplier_bookings(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'active' CHECK(status IN ('active','confirmed','expired','cancelled')),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE booking_folios ADD COLUMN IF NOT EXISTS folio_number VARCHAR(60);
ALTER TABLE booking_folios ADD COLUMN IF NOT EXISTS billed_to_name VARCHAR(190);
ALTER TABLE booking_folios ADD COLUMN IF NOT EXISTS due_date DATE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_folio_number ON booking_folios(folio_number) WHERE folio_number IS NOT NULL;
CREATE TABLE IF NOT EXISTS payment_records (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,booking_id BIGINT REFERENCES supplier_bookings(id) ON DELETE SET NULL,payment_reference VARCHAR(100) NOT NULL,payment_method VARCHAR(30) NOT NULL,amount NUMERIC(12,2) NOT NULL CHECK(amount>0),currency CHAR(3) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'captured' CHECK(status IN ('pending','authorized','captured','refunded','failed')),provider_transaction_id VARCHAR(190),received_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(supplier_id,payment_reference));
CREATE TABLE IF NOT EXISTS payment_allocations (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,payment_id BIGINT NOT NULL REFERENCES payment_records(id) ON DELETE CASCADE,folio_id BIGINT NOT NULL REFERENCES booking_folios(id) ON DELETE CASCADE,amount NUMERIC(12,2) NOT NULL CHECK(amount>0),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(payment_id,folio_id));
CREATE TABLE IF NOT EXISTS hotel_invoices (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,folio_id BIGINT NOT NULL REFERENCES booking_folios(id) ON DELETE RESTRICT,invoice_number VARCHAR(100) NOT NULL,invoice_type VARCHAR(20) NOT NULL DEFAULT 'invoice',recipient_name VARCHAR(190) NOT NULL,recipient_tax_number VARCHAR(80),subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,currency CHAR(3) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','issued','cancelled','sent')),issued_at TIMESTAMPTZ,UNIQUE(supplier_id,invoice_number));
CREATE TABLE IF NOT EXISTS night_audit_runs (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,business_date DATE NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'started' CHECK(status IN ('started','validated','closed','failed','reversed')),validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,room_charges_posted INTEGER NOT NULL DEFAULT 0,performed_by BIGINT REFERENCES supplier_users(id) ON DELETE SET NULL,started_at TIMESTAMPTZ NOT NULL DEFAULT now(),closed_at TIMESTAMPTZ,UNIQUE(property_id,business_date));
CREATE TABLE IF NOT EXISTS hotel_staff (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,full_name VARCHAR(190) NOT NULL,department VARCHAR(80) NOT NULL,role_code VARCHAR(60) NOT NULL,pin_hash VARCHAR(255),is_active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS hotel_roles (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,role_code VARCHAR(60) NOT NULL,role_name VARCHAR(120) NOT NULL,permissions JSONB NOT NULL DEFAULT '[]'::jsonb,UNIQUE(supplier_id,role_code));
