CREATE TABLE IF NOT EXISTS loyalty_tiers (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,code VARCHAR(40) NOT NULL,name VARCHAR(120) NOT NULL,min_nights INTEGER NOT NULL DEFAULT 0,min_revenue NUMERIC(12,2) NOT NULL DEFAULT 0,stay_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,service_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,bonus_expiry_days INTEGER,UNIQUE(supplier_id,code));
CREATE TABLE IF NOT EXISTS guest_loyalty_accounts (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,guest_id BIGINT NOT NULL REFERENCES guest_profiles(id) ON DELETE CASCADE,tier_id BIGINT REFERENCES loyalty_tiers(id) ON DELETE SET NULL,points_balance NUMERIC(12,2) NOT NULL DEFAULT 0,lifetime_nights INTEGER NOT NULL DEFAULT 0,lifetime_revenue NUMERIC(12,2) NOT NULL DEFAULT 0,status VARCHAR(16) NOT NULL DEFAULT 'active',UNIQUE(guest_id));
CREATE TABLE IF NOT EXISTS loyalty_ledger (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,account_id BIGINT NOT NULL REFERENCES guest_loyalty_accounts(id) ON DELETE CASCADE,booking_id BIGINT REFERENCES supplier_bookings(id) ON DELETE SET NULL,transaction_type VARCHAR(20) NOT NULL CHECK(transaction_type IN ('earn','redeem','expire','adjustment')),points NUMERIC(12,2) NOT NULL,description VARCHAR(255),expires_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS guest_segments (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,name VARCHAR(120) NOT NULL,rules JSONB NOT NULL DEFAULT '{}'::jsonb,is_active BOOLEAN NOT NULL DEFAULT true,UNIQUE(supplier_id,name));
CREATE TABLE IF NOT EXISTS guest_communications (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,guest_id BIGINT REFERENCES guest_profiles(id) ON DELETE SET NULL,booking_id BIGINT REFERENCES supplier_bookings(id) ON DELETE SET NULL,channel VARCHAR(20) NOT NULL CHECK(channel IN ('email','sms','whatsapp','in_app')),template_code VARCHAR(80),subject VARCHAR(190),body TEXT NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'queued',scheduled_at TIMESTAMPTZ,delivered_at TIMESTAMPTZ,error_message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS guest_service_requests (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,booking_id BIGINT NOT NULL REFERENCES supplier_bookings(id) ON DELETE CASCADE,guest_id BIGINT REFERENCES guest_profiles(id) ON DELETE SET NULL,request_type VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'open',priority VARCHAR(12) NOT NULL DEFAULT 'normal',details TEXT,assigned_to BIGINT REFERENCES hotel_staff(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS revenue_snapshots (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,snapshot_date DATE NOT NULL,occupancy_percent NUMERIC(5,2) NOT NULL DEFAULT 0,adr NUMERIC(12,2) NOT NULL DEFAULT 0,revpar NUMERIC(12,2) NOT NULL DEFAULT 0,pickup_count INTEGER NOT NULL DEFAULT 0,cancellation_count INTEGER NOT NULL DEFAULT 0,source_data JSONB NOT NULL DEFAULT '{}'::jsonb,UNIQUE(property_id,snapshot_date));
CREATE TABLE IF NOT EXISTS revenue_recommendations (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,rate_plan_id BIGINT REFERENCES rate_plans(id) ON DELETE SET NULL,stay_date DATE NOT NULL,recommendation_type VARCHAR(30) NOT NULL,recommended_value NUMERIC(12,2),currency CHAR(3),confidence NUMERIC(5,2),reason TEXT,status VARCHAR(16) NOT NULL DEFAULT 'new' CHECK(status IN ('new','accepted','dismissed','applied')),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS report_exports (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,report_type VARCHAR(60) NOT NULL,filters JSONB NOT NULL DEFAULT '{}'::jsonb,format VARCHAR(10) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'queued',file_path TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ);
