<?php
declare(strict_types=1);
require_once __DIR__ . '/database.php';

function ical_escape(string $value): string { return str_replace(["\\", ";", ",", "\r\n", "\n"], ["\\\\", "\\;", "\\,", "\\n", "\\n"], $value); }
function ical_date(string|null $value): ?string { if(!$value) return null; $time=strtotime($value); return $time===false?null:gmdate('Ymd',$time); }
function ical_is_public_host(string $host): bool {
 $host=trim($host,'[]'); if($host==='localhost'||str_ends_with(strtolower($host),'.local'))return false;
 $ips=filter_var($host,FILTER_VALIDATE_IP)?[$host]:gethostbynamel($host); if(!$ips)return false;
 foreach($ips as $ip){if(!filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))return false;} return true;
}
function ical_export_calendar(string $token): ?string {
 $q=db()->prepare("SELECT c.*,p.name FROM ical_connections c JOIN properties p ON p.id=c.property_id WHERE c.access_token=? AND c.direction='export' AND c.status='active'");$q->execute([$token]);$connection=$q->fetch();if(!$connection)return null;
 $q=db()->prepare("SELECT booking_reference,check_in,check_out,status FROM supplier_bookings WHERE property_id=? AND status NOT IN ('cancelled','rejected') AND check_in IS NOT NULL AND check_out IS NOT NULL UNION ALL SELECT external_uid,starts_on,ends_on,event_status FROM ical_events WHERE property_id=? AND event_status NOT IN ('cancelled','cancelled_by_source') ORDER BY 2");$q->execute([$connection['property_id'],$connection['property_id']]);$rows=$q->fetchAll();
 $lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//NEXUS TravelTech//iCal//TR','CALSCALE:GREGORIAN','X-WR-CALNAME:'.ical_escape($connection['name'])];foreach($rows as $row){$start=ical_date($row['check_in']??$row['starts_on']??null);$end=ical_date($row['check_out']??$row['ends_on']??null);if(!$start||!$end)continue;$lines[]='BEGIN:VEVENT';$lines[]='UID:'.ical_escape((string)$row['booking_reference']).'@nexustraveltech.com';$lines[]='DTSTAMP:'.gmdate('Ymd\THis\Z');$lines[]='DTSTART;VALUE=DATE:'.$start;$lines[]='DTEND;VALUE=DATE:'.$end;$lines[]='SUMMARY:'.ical_escape('NEXUS - Reserved');$lines[]='STATUS:CONFIRMED';$lines[]='END:VEVENT';} $lines[]='END:VCALENDAR';return implode("\r\n",$lines)."\r\n";
}
function ical_import_connection(int $connectionId,int $supplierId): array {
 $q=db()->prepare("SELECT * FROM ical_connections WHERE id=? AND supplier_id=? AND direction='import' AND status='active'");$q->execute([$connectionId,$supplierId]);$connection=$q->fetch();if(!$connection)return ['ok'=>false,'message'=>'iCal bağlantısı bulunamadı.'];$url=(string)$connection['source_url'];$parts=parse_url($url);if(!in_array(strtolower((string)($parts['scheme']??'')),['https','http'],true)||empty($parts['host'])||!ical_is_public_host((string)$parts['host']))return ['ok'=>false,'message'=>'Yalnızca genel erişilebilir güvenli iCal URL’leri kullanılabilir.'];if(!function_exists('curl_init'))return ['ok'=>false,'message'=>'Sunucuda cURL etkin değil.'];$curl=curl_init($url);curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>30,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_REDIR_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_USERAGENT=>'NEXUS-iCal/1.0',CURLOPT_MAXFILESIZE=>5*1024*1024]);$body=(string)curl_exec($curl);$err=curl_error($curl);$code=(int)curl_getinfo($curl,CURLINFO_HTTP_CODE);curl_close($curl);if($err!==''||$code<200||$code>=300||strlen($body)>5*1024*1024||!str_contains($body,'BEGIN:VCALENDAR')){db()->prepare("UPDATE ical_connections SET status='error',last_error=? WHERE id=?")->execute([$err?:'HTTP '.$code,$connectionId]);return ['ok'=>false,'message'=>'Takvim indirilemedi: '.($err?:'HTTP '.$code)];}
 $events=preg_split('/BEGIN:VEVENT\r?\n/', $body);$count=0;$up=db()->prepare("INSERT INTO ical_events(ical_connection_id,property_id,external_uid,starts_on,ends_on,summary,event_status,raw_event,synced_at) VALUES(?,?,?,?,?,?,?,?,now()) ON CONFLICT(ical_connection_id,external_uid) DO UPDATE SET starts_on=EXCLUDED.starts_on,ends_on=EXCLUDED.ends_on,summary=EXCLUDED.summary,event_status=EXCLUDED.event_status,raw_event=EXCLUDED.raw_event,synced_at=now()");foreach(array_slice($events,1) as $raw){$event=substr($raw,0,strpos($raw,'END:VEVENT')?:strlen($raw));preg_match('/^UID(?:;[^:]+)?:([^\r\n]+)/mi',$event,$uid);preg_match('/^DTSTART(?:;[^:]+)?:([0-9]{8})/mi',$event,$start);preg_match('/^DTEND(?:;[^:]+)?:([0-9]{8})/mi',$event,$end);preg_match('/^SUMMARY(?:;[^:]+)?:([^\r\n]*)/mi',$event,$summary);preg_match('/^STATUS(?:;[^:]+)?:([^\r\n]*)/mi',$event,$status);if(empty($uid[1])||empty($start[1])||empty($end[1]))continue;$up->execute([$connectionId,$connection['property_id'],trim($uid[1]),DateTimeImmutable::createFromFormat('Ymd',$start[1])->format('Y-m-d'),DateTimeImmutable::createFromFormat('Ymd',$end[1])->format('Y-m-d'),trim($summary[1]??''),strtolower(trim($status[1]??'confirmed')),$event]);$count++;}db()->prepare("UPDATE ical_connections SET status='active',last_sync_at=now(),last_error=NULL WHERE id=?")->execute([$connectionId]);return ['ok'=>true,'message'=>$count.' iCal olayı içe aktarıldı.'];
}
