<?php

require_once __DIR__ . '/database.php';

function default_product_types(): array {
  return [
    'hotel' => ['label' => 'Otel', 'unit' => 'Oda tipi', 'steps' => ['Tesis bilgisi', 'Oda & pansiyon', 'Fiyat & kontenjan', 'Satış kuralları'], 'fields' => [['key'=>'stars','label'=>'Yıldız / sınıf','type'=>'text','placeholder'=>'Örn. 4 yıldız'],['key'=>'room_count','label'=>'Toplam oda','type'=>'number','placeholder'=>'Örn. 48'],['key'=>'board','label'=>'Varsayılan konaklama tipi','type'=>'select','options'=>['Sadece oda','Oda + kahvaltı','Yarım pansiyon','Tam pansiyon','Her şey dahil','Alkolsüz her şey dahil','Ultra her şey dahil']]], 'room_setup'=>true, 'hint' => 'Oda ve villa tiplerinizi, kapasitelerini ve konaklama türlerini bu ilk kurulumda tanımlayın.'],
    'villa' => ['label' => 'Villa', 'unit' => 'Konaklama birimi', 'steps' => ['Villa bilgisi', 'Birim & kapasite', 'Müsaitlik takvimi', 'Fiyat & kurallar'], 'fields' => [['key'=>'bedrooms','label'=>'Yatak odası','type'=>'number','min'=>0,'max'=>50,'placeholder'=>'Örn. 4'],['key'=>'max_guests','label'=>'Maksimum misafir','type'=>'number','min'=>1,'max'=>100,'required'=>true,'placeholder'=>'Örn. 8'],['key'=>'pool','label'=>'Havuz tipi','type'=>'select','options'=>['Özel havuz','Ortak havuz','Havuz yok']],['key'=>'area_m2','label'=>'Alan (m²)','type'=>'number','min'=>0,'max'=>100000,'placeholder'=>'Örn. 180'],['key'=>'floors','label'=>'Kat sayısı','type'=>'number','min'=>0,'max'=>50,'placeholder'=>'Örn. 2'],['key'=>'building_type','label'=>'Yapı tipi','type'=>'select','options'=>['Müstakil','Yarı müstakil','Dubleks','Rezidans']]], 'room_setup'=>true, 'hint' => 'Kapasite, giriş-çıkış günleri ve villa takvimi ile satışa açılır.'],
    'yacht' => ['label' => 'Yat', 'unit' => 'Kabin / yat', 'steps' => ['Yat bilgisi', 'Kabin & kapasite', 'Rota & müsaitlik', 'Kiralama kuralları'], 'fields' => [['key'=>'cabins','label'=>'Kabin sayısı','type'=>'number','min'=>0,'max'=>50,'placeholder'=>'Örn. 4'],['key'=>'guest_capacity','label'=>'Misafir kapasitesi','type'=>'number','min'=>1,'max'=>200,'required'=>true,'placeholder'=>'Örn. 8'],['key'=>'length','label'=>'Yat uzunluğu (m)','type'=>'number','min'=>0,'max'=>500,'step'=>0.1,'required'=>true,'placeholder'=>'Örn. 22'],['key'=>'home_port','label'=>'Bağlama limanı','type'=>'text','placeholder'=>'Örn. Göcek Marina'],['key'=>'crew','label'=>'Mürettebat','type'=>'text','placeholder'=>'Örn. Kaptan + 2 personel'],['key'=>'year_built','label'=>'Yapım yılı','type'=>'number','min'=>1900,'max'=>2100,'placeholder'=>'Örn. 2021']], 'room_setup'=>true, 'hint' => 'Kabin yapısı, rota, liman ve kiralama periyotları ile devam eder.'],
    'tour' => ['label' => 'Tur', 'unit' => 'Tur hareketi', 'steps' => ['Tur bilgisi', 'Program & kalkış', 'Kapasite & fiyat', 'Rezervasyon kuralları'], 'fields' => [['key'=>'duration','label'=>'Süre','type'=>'text','placeholder'=>'Örn. 3 gün / 2 gece'],['key'=>'departure','label'=>'Kalkış noktası','type'=>'text','placeholder'=>'Örn. İstanbul'],['key'=>'capacity','label'=>'Katılımcı kapasitesi','type'=>'number','placeholder'=>'Örn. 40']], 'hint' => 'Tur programı, kalkış tarihleri ve kişi bazlı fiyatlar ile satışa açılır.'],
    'activity' => ['label' => 'Aktivite', 'unit' => 'Seans', 'steps' => ['Aktivite bilgisi', 'Seans & süre', 'Kapasite & fiyat', 'Katılım kuralları'], 'fields' => [['key'=>'duration','label'=>'Süre','type'=>'text','placeholder'=>'Örn. 90 dakika'],['key'=>'meeting_point','label'=>'Buluşma noktası','type'=>'text','placeholder'=>'Örn. Ölüdeniz sahil'],['key'=>'capacity','label'=>'Seans kapasitesi','type'=>'number','placeholder'=>'Örn. 12']], 'hint' => 'Seans saatleri, kapasite ve yaş/katılım koşulları sonraki adımda eklenir.'],
    'cruise' => ['label' => 'Cruise', 'unit' => 'Sefer / kabin', 'steps' => ['Cruise bilgisi', 'Gemi & kabin', 'Rota & sefer', 'Fiyat & kurallar'], 'fields' => [['key'=>'nights','label'=>'Gece sayısı','type'=>'number','placeholder'=>'Örn. 7'],['key'=>'departure_port','label'=>'Kalkış limanı','type'=>'text','placeholder'=>'Örn. Kuşadası'],['key'=>'cabin_capacity','label'=>'Kabin kapasitesi','type'=>'number','placeholder'=>'Örn. 2']], 'hint' => 'Gemi, kabin kategorileri, limanlar ve sefer tarihleriyle devam eder.'],
    'car_rental' => ['label' => 'Araç', 'unit' => 'Araç sınıfı', 'steps' => ['Araç bilgisi', 'Sınıf & özellik', 'Teslim noktaları', 'Günlük fiyat & kurallar'], 'fields' => [['key'=>'vehicle_class','label'=>'Araç sınıfı','type'=>'text','placeholder'=>'Örn. SUV'],['key'=>'seats','label'=>'Koltuk sayısı','type'=>'number','placeholder'=>'Örn. 5'],['key'=>'transmission','label'=>'Vites','type'=>'select','options'=>['Otomatik','Manuel','Elektrikli']]], 'hint' => 'Araç filosu, teslim noktaları, yaş şartları ve günlük fiyatlar sonraki adımda tanımlanır.'],
    'transfer' => ['label' => 'Transfer', 'unit' => 'Güzergâh / araç', 'steps' => ['Transfer bilgisi', 'Güzergâh & araç', 'Kapasite & zaman', 'Fiyat & koşullar'], 'fields' => [['key'=>'pickup','label'=>'Alış noktası','type'=>'text','placeholder'=>'Örn. Dalaman Havalimanı'],['key'=>'dropoff','label'=>'Varış noktası','type'=>'text','placeholder'=>'Örn. Fethiye'],['key'=>'vehicle_capacity','label'=>'Araç kapasitesi','type'=>'number','placeholder'=>'Örn. 6']], 'hint' => 'Tek yön/çift yön, araç sınıfı, saat aralığı ve güzergâh fiyatları ile devam eder.'],
    'bus' => ['label' => 'Otobüs', 'unit' => 'Sefer / koltuk', 'steps' => ['Firma & araç bilgisi', 'Güzergâh & duraklar', 'Koltuk & sefer saati', 'Bilet fiyatı & kurallar'], 'fields' => [['key'=>'operator','label'=>'Otobüs firması / işletmeci','type'=>'text','placeholder'=>'Örn. NEXUS Seyahat'],['key'=>'vehicle_make','label'=>'Otobüs markası','type'=>'text','placeholder'=>'Örn. Mercedes-Benz'],['key'=>'vehicle_model','label'=>'Otobüs modeli','type'=>'text','placeholder'=>'Örn. Tourismo 16 RHD'],['key'=>'model_year','label'=>'Model yılı','type'=>'number','placeholder'=>'Örn. 2025'],['key'=>'vehicle_class','label'=>'Araç tipi','type'=>'select','options'=>['2+1 turizm otobüsü','2+2 turizm otobüsü','VIP midibüs','Minibüs']],['key'=>'seat_capacity','label'=>'Koltuk kapasitesi','type'=>'number','placeholder'=>'Örn. 46'],['key'=>'departure','label'=>'Kalkış noktası','type'=>'text','placeholder'=>'Örn. İstanbul Esenler Otogarı'],['key'=>'arrival','label'=>'Varış noktası','type'=>'text','placeholder'=>'Örn. Antalya Otogarı'],['key'=>'luggage_policy','label'=>'Bagaj hakkı','type'=>'text','placeholder'=>'Örn. Kişi başı 2 parça / 30 kg'],['key'=>'service','label'=>'İkram / servis','type'=>'select','options'=>['Yok','Su ikramı','Sıcak-soğuk ikram','İkram ve Wi-Fi']]], 'hint' => 'Otobüs firması; araç marka-model-yıl bilgisini, güzergâh, durak, koltuk planı, hareket saati, bilet fiyatı ve iptal kuralını sonraki adımda tanımlar.'],
    'ferry' => ['label' => 'Feribot', 'unit' => 'Sefer', 'steps' => ['Sefer bilgisi', 'Güzergâh & saat', 'Koltuk & kapasite', 'Fiyat & bilet kuralları'], 'fields' => [['key'=>'departure_port','label'=>'Kalkış limanı','type'=>'text','placeholder'=>'Örn. Bodrum'],['key'=>'arrival_port','label'=>'Varış limanı','type'=>'text','placeholder'=>'Örn. Kos'],['key'=>'capacity','label'=>'Yolcu kapasitesi','type'=>'number','placeholder'=>'Örn. 250']], 'hint' => 'Sefer saatleri, yolcu/araç sınıfları ve bilet kuralları sonraki adımda eklenir.'],
    'restaurant' => ['label' => 'Restoran', 'unit' => 'Masa / oturum', 'steps' => ['Restoran bilgisi', 'Masa & oturum', 'Menü & kapasite', 'Rezervasyon kuralları'], 'fields' => [['key'=>'cuisine','label'=>'Mutfak türü','type'=>'text','placeholder'=>'Örn. Akdeniz'],['key'=>'table_count','label'=>'Masa sayısı','type'=>'number','placeholder'=>'Örn. 25'],['key'=>'seating_capacity','label'=>'Oturma kapasitesi','type'=>'number','placeholder'=>'Örn. 80']], 'hint' => 'Oturum saatleri, masa düzeni, menü seçenekleri ve rezervasyon kuralları ile devam eder.'],
    'cinema' => ['label' => 'Sinema', 'unit' => 'Salon / seans', 'steps' => ['Sinema bilgisi', 'Salon & koltuk', 'Film & seans', 'Bilet fiyatı'], 'fields' => [['key'=>'hall_count','label'=>'Salon sayısı','type'=>'number','placeholder'=>'Örn. 4'],['key'=>'seat_capacity','label'=>'Toplam koltuk','type'=>'number','placeholder'=>'Örn. 240'],['key'=>'format','label'=>'Gösterim formatı','type'=>'select','options'=>['2D','3D','IMAX','VIP']]], 'hint' => 'Salon planı, filmler, seanslar ve koltuk bazlı biletleme sonraki adımda tanımlanır.'],
    'beach' => ['label' => 'Plaj', 'unit' => 'Şezlong / alan', 'steps' => ['Plaj bilgisi', 'Alan & şezlong', 'Oturum & kapasite', 'Fiyat & giriş kuralları'], 'fields' => [['key'=>'beach_type','label'=>'Plaj türü','type'=>'select','options'=>['Özel plaj','Beach club','Halk plajı hizmeti']],['key'=>'sunbeds','label'=>'Şezlong sayısı','type'=>'number','placeholder'=>'Örn. 120'],['key'=>'capacity','label'=>'Günlük kapasite','type'=>'number','placeholder'=>'Örn. 250']], 'hint' => 'Alanlar, günlük giriş, şezlong paketleri ve saat aralıkları ile satışa açılır.'],
    'event' => ['label' => 'Etkinlik', 'unit' => 'Etkinlik / bilet', 'steps' => ['Etkinlik bilgisi', 'Mekân & tarih', 'Kategori & kapasite', 'Bilet & kurallar'], 'fields' => [['key'=>'venue','label'=>'Mekân','type'=>'text','placeholder'=>'Örn. Antik Tiyatro'],['key'=>'event_date','label'=>'Etkinlik tarihi','type'=>'date'],['key'=>'capacity','label'=>'Katılımcı kapasitesi','type'=>'number','placeholder'=>'Örn. 1000']], 'hint' => 'Bilet kategorileri, oturma düzeni, tarih ve iade kuralları sonraki adımda eklenir.'],
  ];
}

function default_step_targets(string $code, bool $roomSetup): array {
  // Kurulum sayfasındaki bölüm çapaları: adım 0 her zaman sec-01 (temel bilgiler),
  // oda/birim kurulumu yapan türlerde adım 1 sec-02; diğer adımlar ilan düzenleyicide
  // devam eden bölümleri işaret eder (villa/yat için sec-04, diğerleri için boş).
  $secondary = ($code === 'hotel' || $code === 'villa' || $code === 'yacht') ? 'sec-04' : '';
  return [$roomSetup ? 'sec-01' : 'sec-01', $roomSetup ? 'sec-02' : $secondary, $secondary, $secondary];
}

function product_types(): array {
  try {
    $rows = db()->query('SELECT code,label,unit,steps,fields,step_targets,room_setup,hint FROM product_type_catalog WHERE is_active=true ORDER BY sort_order,code')->fetchAll();
    if ($rows) {
      $types=[];
      foreach($rows as $row) {
        $roomSetup=(bool)$row['room_setup'];
        $types[$row['code']]=['label'=>$row['label'],'unit'=>$row['unit'],'steps'=>json_decode($row['steps'],true)?:[],'fields'=>json_decode($row['fields'],true)?:[],'step_targets'=>json_decode((string)$row['step_targets'],true)?:default_step_targets((string)$row['code'],$roomSetup),'room_setup'=>$roomSetup,'hint'=>$row['hint']];
      }
      return $types;
    }
  } catch (Throwable) {}
  return default_product_types();
}

function seed_product_type_catalog(): void {
  try {
    if ((int)db()->query('SELECT COUNT(*) FROM product_type_catalog')->fetchColumn() > 0) return;
    $insert=db()->prepare('INSERT INTO product_type_catalog(code,label,unit,steps,fields,room_setup,hint,sort_order) VALUES (?,?,?,?,?::jsonb,?,?,?)');
    $sort=10; foreach(default_product_types() as $code=>$type){$insert->execute([$code,$type['label'],$type['unit'],json_encode($type['steps'],JSON_UNESCAPED_UNICODE),json_encode($type['fields'],JSON_UNESCAPED_UNICODE),$type['room_setup'],$type['hint'],$sort]);$sort+=10;}
  } catch (Throwable) {}
}
