<?php

function product_types(): array {
  return [
    'hotel' => ['label' => 'Otel', 'unit' => 'Oda tipi', 'steps' => ['Tesis bilgisi', 'Oda & pansiyon', 'Fiyat & kontenjan', 'Satış kuralları'], 'fields' => [['key'=>'stars','label'=>'Yıldız / sınıf','type'=>'text','placeholder'=>'Örn. 4 yıldız'],['key'=>'room_count','label'=>'Toplam oda','type'=>'number','placeholder'=>'Örn. 48'],['key'=>'board','label'=>'Varsayılan konaklama tipi','type'=>'select','options'=>['Sadece oda','Oda + kahvaltı','Yarım pansiyon','Tam pansiyon','Her şey dahil','Alkolsüz her şey dahil','Ultra her şey dahil']]], 'room_setup'=>true, 'hint' => 'Oda ve villa tiplerinizi, kapasitelerini ve konaklama türlerini bu ilk kurulumda tanımlayın.'],
    'villa' => ['label' => 'Villa', 'unit' => 'Konaklama birimi', 'steps' => ['Villa bilgisi', 'Oda & kapasite', 'Müsaitlik takvimi', 'Fiyat & kurallar'], 'fields' => [['key'=>'bedrooms','label'=>'Yatak odası','type'=>'number','placeholder'=>'Örn. 4'],['key'=>'max_guests','label'=>'Maksimum misafir','type'=>'number','placeholder'=>'Örn. 8'],['key'=>'pool','label'=>'Havuz tipi','type'=>'select','options'=>['Özel havuz','Ortak havuz','Havuz yok']]], 'hint' => 'Kapasite, giriş-çıkış günleri ve villa takvimi ile satışa açılır.'],
    'yacht' => ['label' => 'Yat', 'unit' => 'Kabin / yat', 'steps' => ['Yat bilgisi', 'Kabin & kapasite', 'Rota & müsaitlik', 'Kiralama kuralları'], 'fields' => [['key'=>'cabins','label'=>'Kabin sayısı','type'=>'number','placeholder'=>'Örn. 4'],['key'=>'guest_capacity','label'=>'Misafir kapasitesi','type'=>'number','placeholder'=>'Örn. 8'],['key'=>'length','label'=>'Yat uzunluğu (m)','type'=>'number','placeholder'=>'Örn. 22']], 'hint' => 'Kabin yapısı, rota, liman ve kiralama periyotları ile devam eder.'],
    'tour' => ['label' => 'Tur', 'unit' => 'Tur hareketi', 'steps' => ['Tur bilgisi', 'Program & kalkış', 'Kapasite & fiyat', 'Rezervasyon kuralları'], 'fields' => [['key'=>'duration','label'=>'Süre','type'=>'text','placeholder'=>'Örn. 3 gün / 2 gece'],['key'=>'departure','label'=>'Kalkış noktası','type'=>'text','placeholder'=>'Örn. İstanbul'],['key'=>'capacity','label'=>'Katılımcı kapasitesi','type'=>'number','placeholder'=>'Örn. 40']], 'hint' => 'Tur programı, kalkış tarihleri ve kişi bazlı fiyatlar ile satışa açılır.'],
    'activity' => ['label' => 'Aktivite', 'unit' => 'Seans', 'steps' => ['Aktivite bilgisi', 'Seans & süre', 'Kapasite & fiyat', 'Katılım kuralları'], 'fields' => [['key'=>'duration','label'=>'Süre','type'=>'text','placeholder'=>'Örn. 90 dakika'],['key'=>'meeting_point','label'=>'Buluşma noktası','type'=>'text','placeholder'=>'Örn. Ölüdeniz sahil'],['key'=>'capacity','label'=>'Seans kapasitesi','type'=>'number','placeholder'=>'Örn. 12']], 'hint' => 'Seans saatleri, kapasite ve yaş/katılım koşulları sonraki adımda eklenir.'],
    'cruise' => ['label' => 'Cruise', 'unit' => 'Sefer / kabin', 'steps' => ['Cruise bilgisi', 'Gemi & kabin', 'Rota & sefer', 'Fiyat & kurallar'], 'fields' => [['key'=>'nights','label'=>'Gece sayısı','type'=>'number','placeholder'=>'Örn. 7'],['key'=>'departure_port','label'=>'Kalkış limanı','type'=>'text','placeholder'=>'Örn. Kuşadası'],['key'=>'cabin_capacity','label'=>'Kabin kapasitesi','type'=>'number','placeholder'=>'Örn. 2']], 'hint' => 'Gemi, kabin kategorileri, limanlar ve sefer tarihleriyle devam eder.'],
    'car_rental' => ['label' => 'Araç', 'unit' => 'Araç sınıfı', 'steps' => ['Araç bilgisi', 'Sınıf & özellik', 'Teslim noktaları', 'Günlük fiyat & kurallar'], 'fields' => [['key'=>'vehicle_class','label'=>'Araç sınıfı','type'=>'text','placeholder'=>'Örn. SUV'],['key'=>'seats','label'=>'Koltuk sayısı','type'=>'number','placeholder'=>'Örn. 5'],['key'=>'transmission','label'=>'Vites','type'=>'select','options'=>['Otomatik','Manuel','Elektrikli']]], 'hint' => 'Araç filosu, teslim noktaları, yaş şartları ve günlük fiyatlar sonraki adımda tanımlanır.'],
    'transfer' => ['label' => 'Transfer', 'unit' => 'Güzergâh / araç', 'steps' => ['Transfer bilgisi', 'Güzergâh & araç', 'Kapasite & zaman', 'Fiyat & koşullar'], 'fields' => [['key'=>'pickup','label'=>'Alış noktası','type'=>'text','placeholder'=>'Örn. Dalaman Havalimanı'],['key'=>'dropoff','label'=>'Varış noktası','type'=>'text','placeholder'=>'Örn. Fethiye'],['key'=>'vehicle_capacity','label'=>'Araç kapasitesi','type'=>'number','placeholder'=>'Örn. 6']], 'hint' => 'Tek yön/çift yön, araç sınıfı, saat aralığı ve güzergâh fiyatları ile devam eder.'],
    'ferry' => ['label' => 'Feribot', 'unit' => 'Sefer', 'steps' => ['Sefer bilgisi', 'Güzergâh & saat', 'Koltuk & kapasite', 'Fiyat & bilet kuralları'], 'fields' => [['key'=>'departure_port','label'=>'Kalkış limanı','type'=>'text','placeholder'=>'Örn. Bodrum'],['key'=>'arrival_port','label'=>'Varış limanı','type'=>'text','placeholder'=>'Örn. Kos'],['key'=>'capacity','label'=>'Yolcu kapasitesi','type'=>'number','placeholder'=>'Örn. 250']], 'hint' => 'Sefer saatleri, yolcu/araç sınıfları ve bilet kuralları sonraki adımda eklenir.'],
    'restaurant' => ['label' => 'Restoran', 'unit' => 'Masa / oturum', 'steps' => ['Restoran bilgisi', 'Masa & oturum', 'Menü & kapasite', 'Rezervasyon kuralları'], 'fields' => [['key'=>'cuisine','label'=>'Mutfak türü','type'=>'text','placeholder'=>'Örn. Akdeniz'],['key'=>'table_count','label'=>'Masa sayısı','type'=>'number','placeholder'=>'Örn. 25'],['key'=>'seating_capacity','label'=>'Oturma kapasitesi','type'=>'number','placeholder'=>'Örn. 80']], 'hint' => 'Oturum saatleri, masa düzeni, menü seçenekleri ve rezervasyon kuralları ile devam eder.'],
    'cinema' => ['label' => 'Sinema', 'unit' => 'Salon / seans', 'steps' => ['Sinema bilgisi', 'Salon & koltuk', 'Film & seans', 'Bilet fiyatı'], 'fields' => [['key'=>'hall_count','label'=>'Salon sayısı','type'=>'number','placeholder'=>'Örn. 4'],['key'=>'seat_capacity','label'=>'Toplam koltuk','type'=>'number','placeholder'=>'Örn. 240'],['key'=>'format','label'=>'Gösterim formatı','type'=>'select','options'=>['2D','3D','IMAX','VIP']]], 'hint' => 'Salon planı, filmler, seanslar ve koltuk bazlı biletleme sonraki adımda tanımlanır.'],
    'beach' => ['label' => 'Plaj', 'unit' => 'Şezlong / alan', 'steps' => ['Plaj bilgisi', 'Alan & şezlong', 'Oturum & kapasite', 'Fiyat & giriş kuralları'], 'fields' => [['key'=>'beach_type','label'=>'Plaj türü','type'=>'select','options'=>['Özel plaj','Beach club','Halk plajı hizmeti']],['key'=>'sunbeds','label'=>'Şezlong sayısı','type'=>'number','placeholder'=>'Örn. 120'],['key'=>'capacity','label'=>'Günlük kapasite','type'=>'number','placeholder'=>'Örn. 250']], 'hint' => 'Alanlar, günlük giriş, şezlong paketleri ve saat aralıkları ile satışa açılır.'],
    'event' => ['label' => 'Etkinlik', 'unit' => 'Etkinlik / bilet', 'steps' => ['Etkinlik bilgisi', 'Mekân & tarih', 'Kategori & kapasite', 'Bilet & kurallar'], 'fields' => [['key'=>'venue','label'=>'Mekân','type'=>'text','placeholder'=>'Örn. Antik Tiyatro'],['key'=>'event_date','label'=>'Etkinlik tarihi','type'=>'date'],['key'=>'capacity','label'=>'Katılımcı kapasitesi','type'=>'number','placeholder'=>'Örn. 1000']], 'hint' => 'Bilet kategorileri, oturma düzeni, tarih ve iade kuralları sonraki adımda eklenir.'],
  ];
}
