<?php
declare(strict_types=1);
require __DIR__ . '/../config/auth.php';
require __DIR__ . '/../config/database.php';
require_admin();
if (empty($_SESSION['admin_csrf'])) $_SESSION['admin_csrf'] = bin2hex(random_bytes(32));
$types = ['property_type' => 'Tesis tipleri', 'star_rating' => 'Yıldız seviyeleri', 'theme' => 'Otel temaları'];
$message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && hash_equals($_SESSION['admin_csrf'], (string)($_POST['csrf'] ?? ''))) {
  $action = $_POST['action'] ?? '';
  if ($action === 'add') {
    $type = $_POST['taxonomy_type'] ?? ''; $name = trim((string)($_POST['name'] ?? ''));
    if (isset($types[$type]) && $name !== '') { db()->prepare('INSERT INTO hotel_taxonomies (taxonomy_type,name,sort_order) VALUES (?,?,?) ON CONFLICT (taxonomy_type,name) DO NOTHING')->execute([$type,$name,(int)($_POST['sort_order'] ?? 100)]); $message='Yeni seçenek kaydedildi.'; }
  }
  if ($action === 'toggle') { db()->prepare('UPDATE hotel_taxonomies SET is_active=NOT is_active WHERE id=?')->execute([(int)$_POST['id']]); $message='Seçeneğin durumu güncellendi.'; }
}
$rows = db()->query('SELECT * FROM hotel_taxonomies ORDER BY taxonomy_type, sort_order, name')->fetchAll();
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Otel sınıflandırmaları | NEXUS Admin</title><style>body{margin:0;background:#f7f7f2;color:#10211f;font-family:Arial,sans-serif}.wrap{width:min(1100px,calc(100% - 32px));margin:40px auto}.top{display:flex;justify-content:space-between;gap:20px;align-items:center}.brand{font-size:28px;font-weight:800}.brand span{color:#e85f42}.muted{color:#64716d}.back{color:#10211f}.card{background:#fff;border:1px solid #e1e5de;padding:24px;margin-top:24px}.form{display:grid;grid-template-columns:1fr 1fr 120px auto;gap:10px}.form input,.form select,.form button{padding:11px;border:1px solid #d8ded8;background:#fff}.form button{background:#10211f;color:#fff;font-weight:700}.notice{background:#e6f8c7;padding:10px}.groups{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:20px}.group{background:#fff;border:1px solid #e1e5de;padding:18px}.group h2{font-size:17px;margin:0 0 14px}.row{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-top:1px solid #edf0eb;font-size:13px}.off{opacity:.45}.row button{border:0;background:#eef1ea;padding:5px 7px;cursor:pointer}@media(max-width:700px){.form,.groups{grid-template-columns:1fr}}</style></head><body><main class="wrap"><div class="top"><div><div class="brand">N<span>∿</span>XUS Admin</div><p class="muted">Otel tipleri, yıldız seviyeleri ve satış temaları</p></div><a class="back" href="/nexustraveltech/admin/">← Panele dön</a></div><?php if($message): ?><p class="notice"><?= htmlspecialchars($message) ?></p><?php endif; ?><section class="card"><form method="post" class="form"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['admin_csrf']) ?>"><input type="hidden" name="action" value="add"><select name="taxonomy_type"><?php foreach($types as $key=>$label): ?><option value="<?= $key ?>"><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select><input name="name" required maxlength="120" placeholder="Yeni seçenek adı"><input name="sort_order" type="number" value="100" min="0" title="Sıra"><button>+ Ekle</button></form></section><div class="groups"><?php foreach($types as $key=>$label): ?><section class="group"><h2><?= htmlspecialchars($label) ?></h2><?php foreach($rows as $row): if($row['taxonomy_type']!==$key) continue; ?><div class="row <?= $row['is_active']?'':'off' ?>"><span><?= htmlspecialchars($row['name']) ?></span><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['admin_csrf']) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button><?= $row['is_active']?'Pasife al':'Aktifleştir' ?></button></form></div><?php endforeach; ?></section><?php endforeach; ?></div></main><?php require_once __DIR__.'/../config/ai_widget.php'; ai_widget('/nexustraveltech/admin/ai-chat','admin_csrf'); ?></body></html>
