<?php
declare(strict_types=1);
require __DIR__ . '/../config/auth.php'; require __DIR__ . '/../config/database.php'; require_admin();
if (empty($_SESSION['admin_csrf'])) $_SESSION['admin_csrf'] = bin2hex(random_bytes(32));
$locales=['tr'=>'Türkçe','en'=>'English','de'=>'Deutsch','ru'=>'Русский','ar'=>'العربية','fr'=>'Français'];
$locale=$_GET['locale'] ?? 'en'; if(!isset($locales[$locale])) $locale='en'; $notice='';
if($_SERVER['REQUEST_METHOD']==='POST' && hash_equals($_SESSION['admin_csrf'],(string)($_POST['csrf']??''))){$locale=$_POST['locale']??'en'; foreach(($_POST['translation']??[]) as $id=>$name){$name=trim((string)$name); if($name!=='') db()->prepare('INSERT INTO hotel_taxonomy_translations (taxonomy_id,locale,name) VALUES (?,?,?) ON CONFLICT (taxonomy_id,locale) DO UPDATE SET name=EXCLUDED.name')->execute([(int)$id,$locale,$name]);} $notice='Çeviriler kaydedildi.';}
$rows=db()->prepare('SELECT h.*,COALESCE(t.name, h.name) display_name FROM hotel_taxonomies h LEFT JOIN hotel_taxonomy_translations t ON t.taxonomy_id=h.id AND t.locale=? ORDER BY h.taxonomy_type,h.sort_order,h.name'); $rows->execute([$locale]); $rows=$rows->fetchAll();
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Otel çevirileri | NEXUS Admin</title><style>body{margin:0;background:#f7f7f2;color:#10211f;font-family:Arial,sans-serif}.wrap{width:min(920px,calc(100% - 32px));margin:40px auto}.top{display:flex;justify-content:space-between;align-items:center}.brand{font-size:28px;font-weight:800}.brand span{color:#e85f42}.card{background:#fff;border:1px solid #e1e5de;padding:24px;margin-top:24px}.filters,form{display:grid;gap:12px}.filters{grid-template-columns:220px auto;align-items:end}.row{display:grid;grid-template-columns:180px 1fr;gap:15px;padding:10px 0;border-top:1px solid #e8ece5;font-size:13px}.row input,select,button{padding:10px;border:1px solid #d8ded8;background:#fff}.save{background:#10211f;color:#fff;font-weight:bold}.notice{background:#e6f8c7;padding:10px}.back{color:#10211f}@media(max-width:600px){.row,.filters{grid-template-columns:1fr}}</style></head><body><main class="wrap"><div class="top"><div class="brand">N<span>∿</span>XUS Admin</div><a class="back" href="/nexustraveltech/admin/otel-siniflandirma">← Sınıflandırmalara dön</a></div><?php if($notice): ?><p class="notice"><?= $notice ?></p><?php endif; ?><section class="card"><form method="get" class="filters"><label>Düzenlenen dil<select name="locale" onchange="this.form.submit()"><?php foreach($locales as $key=>$label): ?><option value="<?= $key ?>" <?= $locale===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><p>Boş bırakılan çeviriler varsayılan dilde gösterilir.</p></form></section><form method="post" class="card"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['admin_csrf']) ?>"><input type="hidden" name="locale" value="<?= $locale ?>"><?php foreach($rows as $row): ?><label class="row"><span><?= htmlspecialchars($row['taxonomy_type']) ?><br><b><?= htmlspecialchars($row['name']) ?></b></span><input name="translation[<?= (int)$row['id'] ?>]" value="<?= htmlspecialchars($row['display_name']) ?>"></label><?php endforeach; ?><button class="save">Çevirileri kaydet</button></form></main></body></html>
